### ISSUE TITLE
No clear install instructions

### ISSUE THREAD

**Issue by mrspeaker** [eslint/eslint.github.io#101]
I was told by a coworker that we were moving to eslint, so I came to the website and scoured it looking for the big "install now!" button or some call-to-action... looked through the "configuring eslint" page, then tried the "about" page, then clicked the "latest news link" but the install instructions looked strange as it said it was a "pre-release" version... because I'd clicked on everything else I thought I'd give "Command Line Interface" a go, and for some reason that's where the install instructions were. 

Not a big deal, but I just thought I'd let you know my experience.

**Comment by nzakas** [comment]
Yeah, I can see your confusion. We should probably have that right smack on the homepage. For what it's worth, we do have installation information here: http://eslint.org/docs/user-guide/command-line-interface

**Comment by mrspeaker** [comment]
Yeah, I found them in the end! You can close off this issue - I just wanted to bring it up even though it's minor, because I know it's hard to look at your own docs from the perspective of someone who has no idea about your project - so it's easy to lose people who might otherwise stick around.

**Comment by IanVS** [comment]
The `eslint --init` initialization wizzard is a great first step for beginners.  How about a big button that provides download instructions, first steps (like the `--init` wizzard) and a super-basic explanation of concepts with links to dive in deeper?
