### ISSUE TITLE
Demo: Export settings function

### ISSUE THREAD

**Issue by robotvert** [eslint/eslint.github.io#110]
Hi,

Recently I had to setup a new dev machine, including re-installing things like eslint.

Couldn't remember how to start using it so I went to the demo page and found myself searching for some "export these settings" functionality.

I don't know how people use the demo page but if trivial to make that functionality might be a cool addition.

Just my 2 cents, feel free to close this "issue" at will! :smiley:

**Comment by nzakas** [comment]
I'm not sure how hard it would be. @ilyavolodin any thoughts?

**Comment by ilyavolodin** [comment]
It shouldn't be too hard to add. However, currently rule configuration for the demo only supports on/off mode, and a lot of our rules are configurable. I was planning to add ability to configure rules and at the same time add ability to export selected configuration.

**Comment by xjamundx** [comment]
I will do this.

**Comment by xjamundx** [comment]
Presumably we can either put the output in a modal popup or just use something like https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL (which seems to have decent browser support per http://caniuse.com/#feat=bloburls) to allow them to download a file created dynamically in the browser. Should be a fun project.
