### ISSUE TITLE
Demo: Rules configuration tooltips not including examples

### ISSUE THREAD

**Issue by JamesThorpe** [eslint/eslint.github.io#115]
On the demo page, some of the checkbox tooltips within the Rules Configuration section are written with the intent to include examples.  These examples do not appear as they're not being included in the markup for the toolip:

![image](https://cloud.githubusercontent.com/assets/8236566/9227464/9886614c-410b-11e5-98f3-0e5d0b6818dc.png)

**Comment by JamesThorpe** [comment]
Looks like it's because these are built to automatically read the first paragraph from the documentation pages:

https://github.com/eslint/eslint.github.io/blob/master/js/app/demo.js#L124

Unsure of the best fix at this point, as obviously some of the documentation is quite lengthy.

**Comment by nzakas** [comment]
Thanks, we will take a look.

**Comment by ilyavolodin** [comment]
I don't really think it's fixable. I just grab the first paragraph from the documentation page and hope that it has something that would explain what this rule does. Unfortunately, our documentation doesn't follow strict formatting, so in a lot of cases, first paragraph might be incomplete, or might not explain anything about the rule...

**Comment by JamesThorpe** [comment]
Yeah - completely understand.  Perhaps one approach could be to keep the popovers open for longer, rather than disappearing as soon as you move off the element, and put a "read more..." link in them that goes to the full documentation page?

**Comment by ilyavolodin** [comment]
@JamesThorpe That might solve it. But I think better approach would be to populate tooltip with short rule description from here instead: http://eslint.org/docs/rules/
At least most of those are meaningful.

**Comment by ilyavolodin** [comment]
Demo re-write now pull tooltip information from the rule metadata, so closing this issue.
