### ISSUE TITLE
It's hard to find out if a given rule is on/off by default

### ISSUE THREAD

**Issue by callumlocke** [eslint/eslint.github.io#117]
The top of the [rules](http://eslint.org/docs/rules/) page says:

> Though none are enabled by default, some are specifically recommended by ESLint and may be turned on using [configuration](http://eslint.org/docs/user-guide/configuring).

But I can't find any further explanation of which configuration setting will turn on which rules.

On a specific docs page, e.g. [no-const-assign](http://eslint.org/docs/rules/no-const-assign), there is no mention of if/when the rule is enabled by default. Does this mean the rule is never on-by-default, even with the `es6` env enabled?

It would be helpful if every rule page explicitly stated what its default setting is (0, 1 or 2), and which config conditions can change this default, if any.

**Comment by IanVS** [comment]
The rules which end with `(recommended)` are turned on by extending `ESLint:recommended`.  By default (meaning you've not extended anything or specified any rules or added any plugins), all rules are off.

Perhaps we could make the explanation more clear, by changing the note you reference to something like: 

> Though none are enabled by default, some rules are specifically recommended by ESLint.  These are denoted by "(recommended)" at the end of their descriptions below, and may be turned on using `"extends": "eslint:recommended"` in your [configuration](http://eslint.org/docs/user-guide/configuring).

**Comment by IanVS** [comment]
> Does this mean the rule is never on-by-default, even with the  es6  env enabled?

By the way, after `1.0.0`, setting an `env` will never turn on or off rules.

**Comment by callumlocke** [comment]
That docs wording change looks good to me, thanks.

**Comment by callumlocke** [comment]
Is there a list of all the rules that get turned on by `eslint:recommended`?

It's not mentioned on the [configuring](http://eslint.org/docs/user-guide/configuring#extending-configuration-files) page.

**Comment by callumlocke** [comment]
> By the way, after `1.0.0`, setting an `env` will never turn on or off rules.

What will setting an `env` actually do, if it doesn't turn on or off rules? Is it purely for pre-defining globals?

**Comment by IanVS** [comment]
> Is there a list of all the rules that get turned on by  eslint:recommended ?

This can be found in a few places.  There is a list in the [migrating guide](http://eslint.org/docs/user-guide/migrating-to-1.0.0#all-rules-off-by-default), and they are indicated by `(recommended)` in the [rules list](http://eslint.org/docs/rules/).

Setting `env` defines globals and sets `ecmaFeatures` for the Espree parser.  You can see the definition of the environments in: https://github.com/eslint/eslint/blob/master/conf/environments.js.

**Comment by nzakas** [comment]
Handling this in the ESLint repo.
