### ISSUE TITLE
Demo: Add "Check/Uncheck All Rules" button

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint.github.io#123]
Sometimes I'd like to turn off all rules besides the one I am interested in.  It would be nice if there was a quick way to turn them all off.

**Comment by alberto** [comment]
:+1: Very useful when you want to triage a reported bug, only enabling the rule in question.

**Comment by guerrero** [comment]
This is an easy to achieve functionality, I can try to implement it if no one is working on it

**Comment by ilyavolodin** [comment]
@guerrero There's an open PR for a new version of the demo. It's working, but incomplete. If you want to work on enhancing demo, it might be worth it to work on top of that PR, since it supports functionality that is currently broken in the live demo.

**Comment by guerrero** [comment]
Ah thanks! I'll keep an eye on that PR to check if I can help with anything
