### ISSUE TITLE
Demo's annotations are not 1-based column

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint.github.io#125]
![image](https://cloud.githubusercontent.com/assets/1937871/9537338/cd30690c-4d71-11e5-942e-907bf32b01cb.png)

**Comment by ilyavolodin** [comment]
Yeah, demo was never fixed after 1.0 release.

**Comment by mysticatea** [comment]
Thanks!

**Comment by ilyavolodin** [comment]
Sure, I figured since I can't really force myself to find time to rewrite demo, I might as well fix this issue.
