### ISSUE TITLE
Demo: Update Without OK Button

### ISSUE THREAD

**Issue by xjamundx** [eslint/eslint.github.io#138]
Per #137 we should just let each option automatically update the options.

I can do this.

**Comment by nzakas** [comment]
:+1:

**Comment by mysticatea** [comment]
:+1:

**Comment by mysticatea** [comment]
Yay!

**Comment by mzgol** [comment]
The OK button still exists; is it still needed now?

**Comment by xjamundx** [comment]
It closes the box :)

**Comment by ilyavolodin** [comment]
Ok button is not really needed, but it also doesn't hurt anyone. And in the case where you don't know if update was triggered or not, it's a way to force an update

**Comment by mzgol** [comment]
@ilyavolodin 
> And in the case where you don't know if update was triggered or not, it's a way to force an update

Since the content is already updated it doesn't really force an update but is a noop when it comes to applying rules. But, as @xjamundx wrote, it closes the box so perhaps this is enough to keep it.
