### ISSUE TITLE
Local Storage cache is not auto-clearing

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint.github.io#142]
Since the demo stores all of the rules into local storage, and doesn't have any mechanize for clearing it, new releases do not add new rules to demo for people who viewed the site earlier. We should somehow clear the local storage after every release.

**Comment by kaicataldo** [comment]
Curious how this could be achieved. Could we have a unique id number stashed with the `localStorage` cache that changes/increments with each release that busts the cache if it doesn't match?

**Comment by BYK** [comment]
Can we use `sessionStorage` instead or use ESLint version as the namespace key?

**Comment by ilyavolodin** [comment]
ESLint version as a key might be a good idea. That would make things easy, I think. `sessionStorage` wouldn't help, since the whole idea of the caching will be lost

**Comment by kaicataldo** [comment]
Yeah, I like that idea too! Might try to take a look at this later tonight

**Comment by kaicataldo** [comment]
I'm still not entirely clear on how the ESLint version gets updated - is it a manual thing? Or is it pulled in somewhere and updated programmatically?

**Comment by xjamundx** [comment]
I'm looking at that for #195. I think you have to run `npm run browserify` or `make browserify` or something from the main eslint repo. A bit of magic for sure. I believe there may some sort of automated way the site gets updated. @ilyavolodin will know for sure :)

**Comment by mysticatea** [comment]
I hope "turn all rules off" button.

I'm using the demo after I turned all rules off.
I'm afraid that I must do that on every release...

**Comment by ilyavolodin** [comment]
ESLint version gets updated from the main repository by running `npm run browserify` (or rather by running `npm run minor/major/patch` which will run `npm run gensite` which will run browserify task). `npm run gensite` will automatically update the site, but it will also pull all of the documentation from main repository, so not something you want to do when you just want to update demo page.
