### ISSUE TITLE
Repository lacks .gitignore

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint.github.io#147]
Since there are devDependencies, it's worth adding a `.gitignore` file to ensure `node_modules` don't accidentally get committed.

**Comment by nzakas** [comment]
I'm not sure this is needed. @xjamundx ?

**Comment by ilyavolodin** [comment]
It would also help if you run Jekyll locally, as Jekyll generates `_site` folder where it puts compiled code.

**Comment by platinumazure** [comment]
@nzakas Is it *needed*? No. Is it a best practice to avoid the possibility of a well-intentioned newbie checking in something he or she shouldn't? Yes. Is it the end of the world if someone does commit those folders or files? No- but it's history you don't need in the repo.

@ilyavolodin If you see value in my amending the issue and PR to include `_site`, I can do that. Let me know.

**Comment by xjamundx** [comment]
I personally do like including this as I think it makes it easier for folks working on the project. May not be absolutely needed, but makes it easier for reviewers to not miss accidental check-ins so I'm :+1:

**Comment by ilyavolodin** [comment]
@platinumazure Sorry, lost track of this issue. Yes, could you update PR to include `_site` and I'll merge it in.

**Comment by platinumazure** [comment]
Sorry for the delay- work has been crazy. I will update the pull tonight!
