### ISSUE TITLE
Demo: Demo does not work in Firefox

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint.github.io#156]
I get two errors in Firefox 42.0 (using Firebug console). Unfortunately, I'm not sure which of these are relevant. Sorry.

> ReferenceError: algoliasearch is not defined
>	var client = algoliasearch('XWXG7MEBSB', '653e00f423bee91f9863571eed16f2f5');
> 
> search.js (line 5, col 7)

And:

> TypeError: b is undefined
> ...}),k=d||new h({input:f,eventBus:j,hint:void 0===b.hint?!0:!!b.hint,minLength:b.m...

The second one seems to be from autocomplete.min.js, but not 100% sure.

The odd thing is, I actually get similar errors in Chrome, so... if my diagnostics are useless, I apologize.

**Comment by xjamundx** [comment]
<img width="1236" alt="screen shot 2015-11-13 at 8 54 14 am" src="https://cloud.githubusercontent.com/assets/246143/11151845/25a8f85c-89e4-11e5-8147-feaf62a28257.png">

**Comment by xjamundx** [comment]
I noticed there's no search bar on this page as well, probably the JS that's included is different than the JS for the rest of the site and it's blowing up....

**Comment by ilyavolodin** [comment]
I hate debugging requireJS errors. But it looks like firefox was having issues with `text` plugin for require.

**Comment by xjamundx** [comment]
I can probably fix this if you want. Just give me a day.

**Comment by ilyavolodin** [comment]
Sounds good. Let me know if you will not find anything, I can then take a look at it over the weekend.
