### ISSUE TITLE
Algolia search failing in Travis

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint.github.io#159]
Looks like the Travis setup isn't quite working.

https://travis-ci.org/eslint/eslint.github.io/builds/92346666

@pixelastic any ideas?

**Comment by ilyavolodin** [comment]
Looks like travis config is missing a step to install required gems.

**Comment by pixelastic** [comment]
Hmm, looks like your `master` branch does not have a `Gemfile`, so the `bundle install` run by Travis fails.

This is weird, I thought I added the `Gemfile` to my PR, but I check and it is not in it. In any case, here is the content of the `Gemfile` I have on my laptop, that should work:

```ruby
source 'https://rubygems.org'

gem 'jekyll', '~> 2.5.3'

group :jekyll_plugins do
  gem 'algoliasearch-jekyll', '~> 0.5.1'
  gem 'jekyll-sitemap', '~> 0.8.1'
  gem 'jekyll-redirect-from', '~> 0.8.0'
end
```

**Comment by pixelastic** [comment]
I can submit a PR with the missing file if you prefer.

**Comment by gyandeeps** [comment]
Sure. Thanks
