### ISSUE TITLE
Git Precommit Hook doesn't check new files

### ISSUE THREAD

**Issue by arnaugm** [eslint/eslint.github.io#165]
The **Git Precommit Hook** suggested in the *Integrations* page doesn't check new created files. Shouldn't be interesting to provide a more robust hook?

**Comment by nzakas** [comment]
Those links are submitted by others. If you have a link to add, feel free to send a pull request.

**Comment by arnaugm** [comment]
No I don't have one sorry. I'll open a PR if I find it.

**Comment by nzakas** [comment]
OK, in the meantime I'm going to close this. Feel free to send in the PR if/when you find something.
