### ISSUE TITLE
CommonJS recommendation + `global` variable

### ISSUE THREAD

**Issue by isiahmeadows** [eslint/eslint.github.io#169]
In http://eslint.org/docs/user-guide/configuring#specifying-environments, it specifies to use `commonjs`, not `node` for Browserify/Webpack/etc. The most common CommonJS implementations have a `global` variable, even though it's not mandated in the CommonJS spec, mostly following Node's lead. In browsers, `global` is an alias for `window`.

Could this recommendation be either fixed/clarified on the website or patched in ESLint proper?

(cross-posted in https://github.com/eslint/eslint/issues/4728, as it applies there, also)

**Comment by nzakas** [comment]
Let's track this on the ESLint repo.
