### ISSUE TITLE
Better documentation of config by comment

### ISSUE THREAD

**Issue by wheresrhys** [eslint/eslint.github.io#172]
Am I blind, or are the only docs for config using inline comments now in the cli docs http://eslint.org/docs/user-guide/command-line-interface#no-inline-config? Either they've gone from elsewhere, or have become harder to find in the last few days ( a few days ago I found them with no problem)

**Comment by ilyavolodin** [comment]
The link you provided is a new option that was added recently to disallow any inline configurations. Documentation for inline configuration is where it's always been: http://eslint.org/docs/user-guide/configuring#configuring-rules I agree it's not the most clean way of showing it, but I'm not sure how we can make it better.

**Comment by kaicataldo** [comment]
Closing this issue as it looks like the question has been answered. Please feel free to visit us in the [ESLint Gitter](https://gitter.im/eslint/eslint) if you have any other issues!
