### ISSUE TITLE
Search bar defaults to returning results in 2.0.0

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint.github.io#177]
According to the latest [news](http://eslint.org/blog/2016/01/eslint-v2.0.0-beta.1-released/) the ESLint beta release isn't intended for production use. 

However:

- the documentation search bar always pulls up the 2.0 docs (even if I manually change the url to 1.0.0)
- there's nothing in the UI of the site to switch back to an older version, or even indicate which version is being viewed (it's visible in the browser url, but that's the only place)

This all seems counterintuitive, especially if production use of 2.0.0 is being discouraged.

**Comment by nzakas** [comment]
@pixelastic is there a way to exclude certain directories from the search?

**Comment by pixelastic** [comment]
Yes, it is possible to exclude pages from the custom hooks. I'll submit a PR if you want.
