### ISSUE TITLE
Documentation about --fix

### ISSUE THREAD

**Issue by angelozerr** [eslint/eslint.github.io#189]
It should be cool if we could have a documentation:

 * which list the whole rules which supports fix like http://eslint.org/blog/2015/10/eslint-v1.6.0-released/
 * for each rule, like https://github.com/eslint/eslint.github.io/blob/master/docs/rules/brace-style.md to know if the rule support fix or not and better show a sample of the fix.

**Comment by ilyavolodin** [comment]
You can see all of the rules that support fixes here: http://eslint.org/docs/rules/ and each rule that supports fixing should mention it in the documentation: http://eslint.org/docs/rules/no-extra-semi Are you looking for something else?

**Comment by angelozerr** [comment]
Thanks @ilyavolodin for your answer. 

> Are you looking for something else?

Sorry for my question, your doc is very good, I have none seen it.
