### ISSUE TITLE
Eclipse support for ESLInt

### ISSUE THREAD

**Issue by angelozerr** [eslint/eslint.github.io#190]
Is it possible to add [Eclipse support for ESLint](https://github.com/angelozerr/tern.java/wiki/Tern-Linter-ESLint)  inside http://eslint.org/docs/user-guide/integrations.html

**Comment by ilyavolodin** [comment]
Sure. Do you want to send a pull request to this file: https://github.com/eslint/eslint.github.io/blob/master/docs/user-guide/integrations.md ?

**Comment by angelozerr** [comment]
Thanks @ilyavolodin for your answer. I have done a PR for that https://github.com/eslint/eslint.github.io/pull/191
