### ISSUE TITLE
Add search tracking to GA

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint.github.io#192]
We added site search through Algolia, but we are not tracking search terms through GA. It would be helpful to add that in, since it might give us a good insight into what people are searching for.

**Comment by pixelastic** [comment]
FYI, you have access to analytics data in your Algolia dashboard. It displays things like most common queries, most common queries without results, number of words typed, and all that including or excluding typos.

You only had 1 day of analytics retention, I just bumped it to 30 days.
