### ISSUE TITLE
Update site for Jekyll 3

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint.github.io#194]
I already got an email notification saying that redcarpet will be disabled on May 1st. We should update the site to use kramdown and see if we can also enable any of the new features.

**Comment by nzakas** [comment]
What new features are there?

**Comment by ilyavolodin** [comment]
Nothing jumps out right away, other then switching code colorization to native ruby (so we should start getting color for code highlighting). But I think kramdown has a few nice features vs. redcarpet, like affix and eee... something else, can't remember right now.

**Comment by ilyavolodin** [comment]
Btw, @nzakas do you remember the reason we are currently using redcarpet? Anything I should be looking for while converting to kramdown?

**Comment by nzakas** [comment]
I think it had something to do with the code fences, but can't recall anything specific.

**Comment by ilyavolodin** [comment]
I remember having issues with unicode characters at some point, and that might've been the cause, but maybe it was code fences. Anyways, I'll try converting it to kramdown and do a few smoke tests.

**Comment by pedrottimark** [comment]
Well, this is timely. The header of a table is optional in kramdown, unlike other dialect of markdown. I will explore and prototype what lists of rules would look like as tables, because it would be possible with this change.

**Comment by ilyavolodin** [comment]
I tried doing this today, and ran into a bunch of issues. All code wells seems to be broken, H1s are not rendering correctly, etc. I'm not really sure why this is happening. I'll try to take a look at it more.

**Comment by ilyavolodin** [comment]
Well, great. Was just reading kramdown issue tracker, and apparently they do not support fenced code blocks with \`\`\` syntax. They are saying that it's something that Github invented, and it's not part of the markdown spec. So it looks like we have to replace all \`\`\` with \~\~\~. Still not sure about H1s. They seem to be working on the homepage, but not in rule documentation.

**Comment by ilyavolodin** [comment]
Figured it out. You have to have a linebreak on the line before H1 for it to render... I'm not entirely sure what Github was thinking when they forced the switch to kramdown, since it doesn't even support their own syntax... Guess I'll have to fix release script to make all of those changes on the fly.

**Comment by ilyavolodin** [comment]
Nevermind. Apperantly issues that I found on kramdown tracker were old, they do support Github fenced code style, just need to enable an option for that.
