### ISSUE TITLE
Update demo for 2.0.0

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint.github.io#195]
The demo still has "modules" under `ecmaFeatures`. We should probably change this to be `sourceType` with a radio or dropdown for "Script" or "Module".

I can't for the life of me figure out how that information is populated. :)

**Comment by xjamundx** [comment]
It was some crazy magic when we did it before. Something to do with the browserify bundling or something. Total madness. :)

**Comment by nzakas** [comment]
I was looking at parser.index.js....seems like that was generated somewhere else?

**Comment by xjamundx** [comment]
https://github.com/eslint/eslint.github.io/blob/master/package.json#L11

`npm run build`

**Comment by Narretz** [comment]
This would be very nice, because at the moment you cannot use imports in the demo, as you cannot set sourceType module.

**Comment by ilyavolodin** [comment]
This PR https://github.com/eslint/eslint.github.io/pull/235 fixes sourceType, but it's not 100% complete. One thing that is missing in it is ability to click on the error and have cursor move to that line, as well as error bubbles in the editor.

**Comment by kaicataldo** [comment]
Is this done now? Looks like the ESLint demo has the source type drop down!

**Comment by vitorbal** [comment]
It does look like this is done now, so closing this!
