### ISSUE TITLE
Update parser demo

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint.github.io#196]
The parser demo needs to be updated with the correct options for the new version of Espree. So, it should have ecmaVersion as an option and allow you to specify `sourceType` as "script" or "module".

@xjamundx I couldn't quite tell how the parser demo was built, can you take a look (and also, can you add some docs in the readme about how to build the parser demo files)?

**Comment by xjamundx** [comment]
Sure thing. Give me a few days.

**Comment by nzakas** [comment]
Thanks!

**Comment by xjamundx** [comment]
80% done

**Comment by xjamundx** [comment]
Okay I think this is done, only question is why does `eslint.js` only include `espree 2.2.5`
