### ISSUE TITLE
Update demo to use CodeMirror

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint.github.io#21]
Change the text entry to use CodeMirror so we can see lint errors inline. Code donated from here: 
https://github.com/angelozerr/codemirror-lint-eslint

We just need to integrate it.

**Comment by ilyavolodin** [comment]
It looks like it should be possible to do with Orion as well, They have Annotations that would do exactly the same thing. Unfortunately their documentation is not really great. @mamacdon would you be able to help us with this? As far as I understand it should be possible to add annotations through `editor.getAnnotationsModel().addAnnotation()` but I don't fully understand what goes into it, and what to do with it later. I'm not sure if you know anything about it.

**Comment by mamacdon** [comment]
Hey guys. There's an easier way: `editor.showProblems(Problem[])` where each Problem looks like [this](https://wiki.eclipse.org/Orion/Documentation/Developer_Guide/Plugging_into_the_editor#The_Problem_object).

Here's a fix that worked for me: https://github.com/mamacdon/eslint.github.io/commit/fc0670351a0dcdbb88233f3d987e226d46045b31

It's not perfect:
* I set the `end` offset for each annotation to `start + 1`. Ideally you'd want to show the annotations on the actual source range of the relevant AST node/token that was flagged by the rule -- that's what we do in the full-blown Orion product. The `eslint.verify()` API doesn't seem to expose detailed range info, but you would know better than I.
* The Orion editor doesn't support displaying annotations at EOL+1 (like Sublime Text has), so "trailing whitespace" errors get dropped.
* "Missing newline at eof" is in a weird spot.

**Comment by mamacdon** [comment]
Also, the Orion jsdoc in this area is poor, I'll try to improve it. Thanks for pointing it out.

**Comment by ilyavolodin** [comment]
Awesome! Thanks for the help @mamacdon I'll create a pull request for this.
