### ISSUE TITLE
Algolia push fails in Travis

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint.github.io#216]
I just upgraded site to use kramdown and jekyll 3.0, but now algolia push fails with every Travis build with the following message:
```
Bundled gems are installed into ./vendor/bundle.
22.27s$ bundle exec jekyll algolia push
Configuration file: /home/travis/build/eslint/eslint.github.io/_config.yml
     Build Warning: Layout 'none' requested in feed.xml does not exist.
jekyll 3.0.3 | Error:  undefined method `to_sym' for nil:NilClass
The command "bundle exec jekyll algolia push" exited with 1.
```
@pixelastic any chance you can help with this? I really don't know anything about ruby.

Also two other search related questions that I had were:
* Is there a way to tie in Algolia search with google analytics somehow?
* Search results seem to be adding `.html` extension to all search results, which confuses google with a bunch of duplicate pages, any way to remove that?

**Comment by pixelastic** [comment]
I'll have a look at this. I already fixed a few issues with Jekyll 3, but I might have overlooked something.

Regarding integration with Analytics, we have nothing out of the box, but you can plug whatever code you want to the event fired when a result is selected in the list:
https://github.com/eslint/eslint.github.io/blob/master/js/app/search.js#L77-L80

Regarding the `html` file, you can have more control over which pages get indexed or not [here](https://github.com/eslint/eslint.github.io/blob/master/_plugins/search.rb#L38-L57). If this is not enough, you can also override `AlgoliaSearchRecordExtractor.custom_hook_all` (in the same file) with your own methods that takes the list of records to index as input and expect a filtered list as output. This means that you could write your own filtering logic (deduplicating elements) in this method before it is send the Algolia index.

I'd be happy to help you with that, but I don't know the specifics enough to provide a PR :)

**Comment by ilyavolodin** [comment]
@pixelastic If you could take a look at the build issue, that would be great. Everything else is not critical, and I can look into it myself (analytics and `.html`).

**Comment by pixelastic** [comment]
I've submitted a PR on the `jekyll` branch. Tell me if this fixes the issue :)

**Comment by ilyavolodin** [comment]
@pixelastic Travis is not successfully completes and pushes updates to Algolia. Thanks again for your help!
