### ISSUE TITLE
Website search is broken

### ISSUE THREAD

**Issue by gkrinc** [eslint/eslint.github.io#224]
When searching on the website (http://eslint.org/) on any page, search.js throws errors

```
  // Calls the Algolia API to get results matching the query
  function autocompleteSource(query, callback) {
    client.search([{
      indexName: 'eslint',
      query: query,
      params: {
        hitsPerPage: 5
      }
    }], function (err, data) {
      callback(formatHits(data.results[0].hits));   //<--- this line throws the error: line 21
    });
  }
```

<img width="1377" alt="screen shot 2016-03-14 at 10 56 52 am" src="https://cloud.githubusercontent.com/assets/2718382/13748508/7f94d86e-e9d3-11e5-8ca3-4609d64aa3e0.png">

**Comment by nzakas** [comment]
Hmmm. It seems to be working OK for me. What browser and version are you using?

**Comment by pedrottimark** [comment]
For your info, a quick test seems okay on OS X 10.11.3 for all of the following:
* Chrome 49 stable
* Firefox 45 stable and 47 aurora
* Opera 35 stable
* Safari 9.0.3 stable

**Comment by gkrinc** [comment]
Chrome v48.0.2564.166

On Mon, Mar 14, 2016 at 12:46 PM, Nicholas C. Zakas <
notifications@github.com> wrote:

> Hmmm. It seems to be working OK for me. What browser and version are you
> using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eslint/eslint.github.io/issues/224#issuecomment-196405707>
> .
>



-- 
*Greg Smith*
*President*
GKR Enterprises Inc

**Comment by nzakas** [comment]
@gkrinc and you're on Windows?

**Comment by gkrinc** [comment]
Nope, on Mac OS 10.11.4 and updated to Chrome v49 and I'm still seeing the
issue :(

On Mon, Mar 14, 2016 at 1:08 PM, Nicholas C. Zakas <notifications@github.com
> wrote:

> @gkrinc <https://github.com/gkrinc> and you're on Windows?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eslint/eslint.github.io/issues/224#issuecomment-196415096>
> .
>



-- 
*Greg Smith*
*President*
GKR Enterprises Inc

**Comment by ilyavolodin** [comment]
@gkrinc It's possible that this is happening because you are running mobile emulator inside chrome. Based on the error message, your Chrome is not respecting cross-origin headers for AJAX calls, so either something is stripping them out (maybe Chrome, maybe proxy server or firewall), or something is wrong with Chrome setup.

**Comment by nzakas** [comment]
Hmm, ad blocker maybe?

**Comment by gkrinc** [comment]
No ad blocker running.

It fails in all OSX browsers: Chrome, Firefox and Safari. Also, fails in
Chrome on Windows.

I shut off all dev tools to see if that was the problem and it wasn't. Ajax
calls on other website work just fine. Definitely looks like a CORS issue
though:

XMLHttpRequest cannot load
http://xwxg7mebsb-dsn.algolia.net/1/indexes/*/queries?x-algolia-api-key=653…id=XWXG7MEBSB&x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%203.8.1.
No 'Access-Control-Allow-Origin' header is present on the requested
resource. Origin 'http://eslint.org' is therefore not allowed access.

On Mon, Mar 14, 2016 at 3:52 PM, Nicholas C. Zakas <notifications@github.com
> wrote:

> Hmm, ad blocker maybe?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eslint/eslint.github.io/issues/224#issuecomment-196495674>
> .
>



-- 
*Greg Smith*
*President*
GKR Enterprises Inc

**Comment by btmills** [comment]
Those headers are normally present, so as @ilyavolodin said, something must be stripping them. Can you try from your phone over data and over wifi?

**Comment by gkrinc** [comment]
You're right. It works fine on my phone using cell data but doesn't work
over WiFi :s

I'll talk to my network guys.

On Tue, Mar 15, 2016 at 10:48 AM, Brandon Mills <notifications@github.com>
wrote:

> Those headers are normally present, so as @ilyavolodin
> <https://github.com/ilyavolodin> said, something must be stripping them.
> Can you try from your phone over data and over wifi?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
>
> https://github.com/eslint/eslint.github.io/issues/224#issuecomment-196852225
>



-- 
*Greg Smith*
*President*
GKR Enterprises Inc

**Comment by ilyavolodin** [comment]
Most likely you have a firewall/proxy in place that strips out headers that it's not aware of (pretty standard feature), and apparently it's not aware of Access-Control headers (that's not standard, might be a VERY old proxy). Closing, as it looks like it's not an issue for most people.
