### ISSUE TITLE
Remove ESLint cla page

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint.github.io#254]
We should take down http://eslint.org/cla/, now that we use the jQuery CLA.

**Comment by gustavnikolaj** [comment]
I wanted to quickly fix this as I did the above referenced PR, but I opted out of it again. I don't believe that it should just be deleted, as there is multiple references to the existing CLA page in among other things [older versions of the documentation](https://github.com/eslint/eslint.github.io/search?q=cla&type=Code&utf8=%E2%9C%93).

The appropriate fix seems to be replacing the `cla/index.md` content with a link to the [jQuery Foundation CLA](https://contribute.jquery.org/cla) as well as a short explanation of why it is necessary and why it's the jQuery one. But I'm not sure I'm the right one to formulate that bit :-)

**Comment by IanVS** [comment]
I like that plan, sounds good.

**Comment by nzakas** [comment]
I'd just make it a redirect to the jQuery one.

**Comment by vitorbal** [comment]
working on this.
