### ISSUE TITLE
Add rule configuration option to the demo

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint.github.io#26]
ESLint has a ton of different rules, I think it would be good to add ability for users to play with different rules on the demo page. For that, we need to expose a way to configure them. It would be even cooler, if we would allow to use plugins, but I don't think that's possible with the current setup.

**Comment by nzakas** [comment]
Plugins are a stretch, but options would be nice.

**Comment by ilyavolodin** [comment]
Correct me if I'm wrong, but currently, there's absolutely no way to do plugins in a browser, right? That feels like an oversight, maybe that should be looked into.

**Comment by nzakas** [comment]
You are correct. It's not an oversight - ESLint is made primarily to be used on the command line. We only create a browserified bundle for demo purposes, but it's in no way meant to have all the functionality available on the command line.

**Comment by ilyavolodin** [comment]
I was thinking more in terms of Orion, but I guess, they are forking ESLint anyways, if they want plugin support, they should be able to add it in.

**Comment by nzakas** [comment]
Yeah, they just need to create a plugin loader and it should work fine.

**Comment by ilyavolodin** [comment]
I started looking into this, and the biggest problem that I see is rule configuration options. We do not have central place that lists all available options for rules, and in order to make this even remotely user friendly, I would need to list config options as something like checkboxes.
I also do not want to maintain options separately from rules themselves, because that means that the page will need to be updated every time there's a change to the rule. I think in general it would be a good idea to add rules options somewhere in the ESLint code. It will help not only with this case, but also will help other people who create editor integrations, and it would be useful for documentation purposes.

**Comment by nzakas** [comment]
I think in the short term it makes sense to just toggle options off or on rather than configuring them completely.

We do have this issue open to figure out how to deal with rule options more sanely: https://github.com/eslint/eslint/issues/967
