### ISSUE TITLE
Website search tray obscured

### ISSUE THREAD

**Issue by Sidewinder1138** [eslint/eslint.github.io#262]
On the eslint.org website, when you start typing in to the search bar, the tray no longer appears properly, but is instead clipped:
![search_tray_cutoff](https://cloud.githubusercontent.com/assets/17938200/15943845/b6205ae2-2e3f-11e6-80db-edc22e45a3cb.png)

It's doing the same thing in Chrome and Firefox. I'm using Windows 10, Chrome 51.0.2704.84, Firefox 46.0.1.

**Comment by pedrottimark** [comment]
Thank you. My bad. Fixing ASAP.

**Comment by pedrottimark** [comment]
@Sidewinder1138 Can you verify it works correctly again now?

**Comment by clairebaire** [comment]
I was about to remark on the issue too, but it looks to be working correctly again in Chrome 51 at least.

**Comment by pedrottimark** [comment]
@clairebaire Thank you, we corrected about 30 minutes ago. Does that timing sound about right?

**Comment by clairebaire** [comment]
@pedrottimark It does indeed!

**Comment by pedrottimark** [comment]
Found another style mistake to fix but will wait until Friday in case anything else arises:

Imprecise selector (aimed at anchor link icons) makes rare headings which contain links text color instead of blue. For example, the headings in http://eslint.org/docs/maintainer-guide/

**Comment by Sidewinder1138** [comment]
@pedrottimark Looks OK to me now. Thanks for the quick response!
