### ISSUE TITLE
Docs pages could use more horizontal padding 

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint.github.io#265]
Checking on my Nexus 7, the docs pages are a bit tight on the left and right. We could use some more padding. 

![screenshot_2016-06-13-16-27-34 2](https://cloud.githubusercontent.com/assets/38546/16026564/467bdc6e-3184-11e6-8dae-beb0f60d26de.png)

You'll need to save the file locally to see since GitHub automatically pads images.

**Comment by ilyavolodin** [comment]
Just an FYI, we don't have to worry too much about mobile/tablet. While it's important that the site looks fine on those devices, we only get 2.84% of traffic from mobile and 0.42% from tablets. I don't see that trend changing any time soon. We are a desktop application. Right now, I feel like we sacrificed desktop usability for mobile, which I don't think is the right thing.

**Comment by nzakas** [comment]
Understood, but if it's easy to add some extra padding to make me happy, why not do it? :)

**Comment by pedrottimark** [comment]
@nzakas Thank you for the feedback. Adding now. Glad to make you happy some of the time 😀

**Comment by pedrottimark** [comment]
@ilyavolodin Glad to know what you think are specific **pain points**. Unlimited line length is for my eyes. I installed a browser plugin to override site styles when I started working with y’all, which is drastic for me.

It is good you have the numbers. It is amusing that we are out of the gate at the same time as http://www.apple.com/swift/playgrounds/

Agree with what you say about **desktop application**. Here are ways responsive design might help:

Display rule doc pages as a **pane** in a development environment, like this markdown viewer:
<img width="1280" alt="265 no-unused-expressions md" src="https://cloud.githubusercontent.com/assets/11862657/16125261/e2c3f5e6-33c0-11e6-95b2-951eba4cd0fb.png">

Display some information side-by-side at screen width at least 1600px. What do you think about this quick-and-dirty test of **example code** at 1920px simulated?
<img width="561" alt="265 no-unused-expressions 1920 1080" src="https://cloud.githubusercontent.com/assets/11862657/16125273/f406d8c8-33c0-11e6-9c12-cfb776934c8c.png">

Display English at the right of **Chinese** as another option to interleaved, if useful to audience:
<img width="1280" alt="265 comma-dangle cn alternative" src="https://cloud.githubusercontent.com/assets/11862657/16125282/ffa4ae6c-33c0-11e6-8c04-5cfcea7b691e.png">

Current default option on cn.eslint.org:
<img width="1280" alt="265 comma-dangle cn interleaved" src="https://cloud.githubusercontent.com/assets/11862657/16125289/0fb7f6ec-33c1-11e6-867f-76366c153b59.png">

**Comment by ilyavolodin** [comment]
@pedrottimark Specific pain-points for me currently are:

* Homepage taking full width of the screen. I use superwidescreen monitor and run at 2560x1080 and homepage and demos look really strange on my screen. Resolution statistics for our visitors are below.
* Menu spanning full width of the screen. With content being left-aligned, it take a long time to drag your mouse from left side of the screen to the top-right corner to use navigation.
* Left-aligned content. Again - large screen, looking to the left all the time is a bit unnerving for me.

My no means do I want to discourage you from working on making site better, that's why I didn't voice my opinion as soon as I merged those changes (granted, I should've reviewed them a lot more thoroughly before merging, that one is on me). But those changes came as a surprise to me, and not in a good way.

And I do agree with you about limiting text width for readability. I just think we can find a better way to do that.


**Screen Resolution for Desktop users**:

Screen Resolution | Percentage
------------------------|---------------
1920x1080 | 28.59%
1440x900	| 17.25%
1280x800 | 9.15%
2560x1440 | 8.98%
1920x1200 | 8.50%

**Comment by pedrottimark** [comment]
Yes, the home page and menu are inconvenient for me even on an ordinary laptop screen. I stayed away from those because my experience is in information design. Do you think Omer would be interested? If he is not, I can work on it, but more carefully.

@ilyavolodin Thank you for reading my mind about the screen resolution statistics. Do you think the side-by-side example code is worth the effort to see if it can become robust, after we get past ESLint 3?

Another side-by-side concept I forgot to mention is corresponding ESLint and JSCS rule docs.

**Comment by ilyavolodin** [comment]
In terms of side-by-side examples. Code examples are fine, I don't think they alone will be able to justify discomfort of left-alignment on large screens. Chines site is a separate site, they don't necessarily have to match our styles exactly and can create their own overrides. JSCS rules side-by-side is an interesting concept, but I'm not sure it will be relevant for too long, also it might create confusion.

P.S. Before we do any other major changes to the design, I feel like it's very important to restore Bootstrap theme that the site uses in original Bootstrap code. Right now we are just creating css overrides, which is fine for small things, but it would be a lot more convenient to do it in SCSS or LESS for larger changes. I'll see if I can work on this in the near future.

**Comment by pedrottimark** [comment]
@ilyavolodin Thank you for your patience. Sorry, I just realized how I messed up the menu for you.

Although left alignment simplified the problem enough for me to get this far, it is not essential as the insightful https://github.com/eslint/eslint.github.io/pull/266#issuecomment-226575024 helped me see, so I will work on media queries to limit line length in a centered alignment above some minimum width.

Then I will dig in to see if example code really can work for wide screens like yours. The table gives a helpful variety of screen resolutions to test in responsive design view and also provide more realistic screen pictures for the team to evaluate.

👍 to updating the Bootstrap theme with what we have learned so we can work in SCSS or LESS.

**Comment by ilyavolodin** [comment]
Just to share the pain, here's how the website currently looks for me:-)

![image](https://cloud.githubusercontent.com/assets/1380062/16131598/fd05da02-33dc-11e6-8aea-b5033f194457.png)

**Comment by pedrottimark** [comment]
@ilyavolodin Am taking baseline screen pictures in Chrome responsive design simulator of the style in early May to compare with the current style and the Bootstrap PR style.

Before I go too far, does this home page look accurate for the original style on your monitor?

<img width="747" alt="2560 1080 home" src="https://cloud.githubusercontent.com/assets/11862657/16282688/d4eacb44-3897-11e6-854d-0e2aa0970c08.png">

**Comment by pedrottimark** [comment]
@nzakas Can you paste in a screen shot of current painful site appearance from your desktop computer so I can measure its width and height to give you more realistic examples now and in the future?

**Comment by alberto** [comment]
@pedrottimark let me know if you need help with the styling

**Comment by pedrottimark** [comment]
@alberto Thank you! I invested a good chunk of today getting an overview of Bootstrap.

**Comment by ilyavolodin** [comment]
@pedrottimark Yes that looks good to me. Btw, if you do not feel comfortable modifying CSS for the site, let us know when you need help. Most of us are web developers and feel at home in the midst of complex CSS code:-)

**Comment by pedrottimark** [comment]
@ilyavolodin Thank you too. Changing typography, color, and layout all at once was an unwise risk :(

**Comment by kaicataldo** [comment]
I can help with the styling too - just let me know :) Would love to see this fixed!

**Comment by kaicataldo** [comment]
I'm going to go ahead and make a PR for this - the site is looking really off with everything left-aligned.

**Comment by ilyavolodin** [comment]
I have code ready on my local machine. I'll submit a PR later tonight.

**Comment by kaicataldo** [comment]
Aside from making the horizontal margins `auto`, I noticed the individual paragraph tags have their own arbitrary width, so it's always going to look off. It looks a lot better if you just let it fill the width of its container.

Current:
![screen shot 2016-07-01 at 5 01 14 pm](https://cloud.githubusercontent.com/assets/7041728/16534411/8c887276-3fad-11e6-92de-06dd14c9cd05.png)

With adding `margin: auto;` and removing `width: auto;` from .container and allowing the paragraphs to fill the width of the container, it looks like this:
![screen shot 2016-07-01 at 5 02 54 pm](https://cloud.githubusercontent.com/assets/7041728/16534456/e181103a-3fad-11e6-8dd5-bbe950bd3cbd.png)

**Comment by kaicataldo** [comment]
Also, any idea what happened to the home page? There is no container with a max-width so it all stretches to the edges of the screen

**Comment by ilyavolodin** [comment]
I updated #269 with changes that gets the site back to original look and feel. We can make incremental changes on top of that.

P.S. @kaicataldo limited width on `p` was done to limit line-length and improve readability, I removed that change for now, but I left commended out code that enables it back in much cleaner way.

**Comment by kaicataldo** [comment]
@ilyavolodin Awesome! I'm :+1: for incremental changes :)

**Comment by ilyavolodin** [comment]
Closing this issue, since this change was done a long time ago.
