### ISSUE TITLE
Change titles for rules to be convenient when tab headers are too small

### ISSUE THREAD

**Issue by airato** [eslint/eslint.github.io#268]
Change this 
<img src="https://cloud.githubusercontent.com/assets/4506749/16135045/c10ff674-33d5-11e6-95f4-c0ae65ca0b85.png" width="500"/>

to this 
<img src="https://cloud.githubusercontent.com/assets/4506749/16134964/3c52cc0e-33d5-11e6-836f-60e6e55696f6.png" width="500"/>

Current template is `Rule rule-name - ESLint - Pluggable JavaScript linter`
I suggest something like `rule-name - Rules - ESLint - Pluggable JavaScript linter`

**Comment by ilyavolodin** [comment]
Sounds good.

**Comment by pedrottimark** [comment]
Indeed, and it fits with a related but lesser change to the title of the rules index page:

s/List of available rules/Rules/

**Comment by vitorbal** [comment]
Working on this.

**Comment by vitorbal** [comment]
Closed by eslint/eslint#6888.
