### ISSUE TITLE
eslint.org certificate seems to be expired

### ISSUE THREAD

**Issue by jaapz** [eslint/eslint.github.io#270]
When I go to `https://eslint.org`, I get a warning that the certificate for the site has expired.

**Comment by nzakas** [comment]
We don't have a certificate.

**Comment by jaapz** [comment]
Oh, it looks like when going to https://eslint.org, it's trying to use github's certificate on your domain (probably because it's hosted on github pages?).

Is there a way to maybe use letsencrypt to get a certificate for eslint.org?

**Comment by nzakas** [comment]
GitHub doesn't provide any of these options. We are pretty much stuck unless GitHub ends up supporting certificates for custom domains.

**Comment by ilyavolodin** [comment]
As @nzakas mentioned, GitHub doesn't provide facility to add certificate for custom domains. Closing as there's nothing we can do about this.
