### ISSUE TITLE
Blog: Rule options changelog improvements

### ISSUE THREAD

**Issue by wKich** [eslint/eslint.github.io#281]
Hello. I think, it would be cool to write new/deprecated options for rules in separated section like 'New rules', but 'New options'. For example, in 3.3.0 release added option `props` for rule `no-self-assign`, but it's hard to track this changes in whole log.

**Comment by nzakas** [comment]
It would be cool, but the blog post is done completely by hand and it's hard to identify all new options in each release.

**Comment by vitorbal** [comment]
Doesn't seem like we can do this (at least not for now, maybe in the future we find a way to automate it), so closing this. Thanks for the suggestion, @wKich!
