### ISSUE TITLE
Rules: "no-template-curly-in-string" is listed in the wrong section of the page

### ISSUE THREAD

**Issue by mateatslc** [eslint/eslint.github.io#282]
`no-template-curly-in-string` introduced in v3.3.0 is listed under the http://eslint.org/docs/rules/#possible-errors section currently.
As it is purely ES6 related I feel it should be moved over to the http://eslint.org/docs/rules/#ecmascript-6 section of the page.

**Comment by platinumazure** [comment]
So the real question here seems to be, should all ES6 syntax rules go into the ES6 category, or can a different category be more appropriate depending on the nature of the rule?

It is definitely the case that the rule is for flagging a (pretty subtle) possible error.

Personally I'm wondering if there needs to be one definitive category for a rule (possible error vs best practice vs style) and then other flags (is it ES6 only? Is it primarily about variables? etc.) could be added. But that might be a deeper discussion than @mateatslc had in mind.

**Comment by mateatslc** [comment]
For me categories make the content easier to navigate, digest and reference. I even build my custom ESLint configs around those categories.
"ES6" as a category is anything but future proof though. Think of ES7, ES8, etc...
Some kind of flagging combined with filtering on top of current categories (minus ES6) could improve the rules page/docs IMHO.

**Comment by nzakas** [comment]
This should be opened in the ESLint repo, as that is the source of the documentation.

**Comment by mateatslc** [comment]
@nzakas: you're right, I missed `category` in the _Working with Rules_ guide

closing this here, let's discuss it over at https://github.com/eslint/eslint/issues/7005
