### ISSUE TITLE
Deprecated/removed rules: Multiple replacements could use more padding or separator

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint.github.io#286]
In the [removed rules](http://eslint.org/docs/rules/#removed) section of the rules page, rules with multiple replacements show both replacements as `<a>` tags with no separator or padding in between.

For example, no-arrow-condition is replaced by no-confusing-arrow and no-constant-condition. But the replacement rules rule pretty closely together with only a space between them.

Possible solutions:

* Use an unordered list for rule replacements (most of the time it doesn't exceed two rules, so not a huge vertical space consumer)
* Use CSS to add padding between the links
* Use CSS or page generation to add content between each link (comma/space? forward slash? etc.)

**Comment by vitorbal** [comment]
Makes sense, it does look quite weird now. I think adding a separator between each link would be the easiest solution. Here's a couple of previews how it could look like:

With forward slash:
<img width="675" alt="screenshot 2016-09-12 14 03 45" src="https://cloud.githubusercontent.com/assets/626038/18435148/cc9e016e-78f1-11e6-876e-04851eb6d6a3.png">

With comma:
<img width="765" alt="screenshot 2016-09-12 14 04 32" src="https://cloud.githubusercontent.com/assets/626038/18435164/ec8ba33c-78f1-11e6-902e-b996da2802dc.png">

**Comment by nzakas** [comment]
:+1: for the comma

**Comment by ilyavolodin** [comment]
One request, can we do it through CSS instead of modifying the script? We should be able to do it through `a+a` selector.

**Comment by vitorbal** [comment]
Pushed a PR for this here: #287
