### ISSUE TITLE
ESLint Demo Page

### ISSUE THREAD

**Issue by noahcollins** [eslint/eslint.github.io#3]
Add embeddable text editor. Orion is first choice. Go with Codemirror for the first version if Orion will take too much time and research.

**Comment by TylerEich** [comment]
@nzakas [Here's a Plunk](http://plnkr.co/edit/jUNamd6xKvYWzckqpnBn?p=preview) I threw together today. I can't commit to any future work on this, but it may serve  as a starting point.

Here are some errors:
![editor-error](https://cloud.githubusercontent.com/assets/3460063/5791028/788fe90a-9e84-11e4-8818-55b57578d007.png)

And here's lint-free:
![editor-no-lint](https://cloud.githubusercontent.com/assets/3460063/5791029/7eafbb26-9e84-11e4-9bd2-19e991bbd498.png)

Take it easy 😎
