### ISSUE TITLE
nav#eslint-navbar seems to require JS

### ISSUE THREAD

**Issue by mk-pmb** [eslint/eslint.github.io#303]
It seems the website requires JavaScript just to open navigation items like "Developer guide", even in Firefox v49. It works when I set NoScript to allow executing code from `cdnjs.cloudflare.com`, but I can't see why I should do so for what could probably be done with CSS easily.
Are there special reasons that I can't see right away?
Shall I try and make a CSS fallback? (If so: is hover ok or should I try to make it wait for a click/touch?)

**Comment by mk-pmb** [comment]
In case anyone else has the same problem, the hover hotfix is:
```css
nav .dropdown:hover > ul.dropdown-menu { display: block; }
```

**Comment by vitorbal** [comment]
Not sure what the rest of the team thinks, but I would definitely be 👎  to hover menus. They are terrible usabillity and hard to get right. I'd prefer if we stick to click/touch instead.

**Comment by mk-pmb** [comment]
To clarify: Any of my propsed CSS fallbacks shall be fallbacks for the case time until the JS for opening the menu has loaded. Once it loads, it can add or remove a class in order to deactivate the fallbacks.

I hope that in this case, you prefer hover over malfunction (menu not opening at all).

My offer to try and build a touch menu still stands, though it would require some large changes to the menu's HTML structure.

**Comment by nzakas** [comment]
We should just add regular URLs into "User Guide" and "Developer Guide". I'm not sure why they're not already there, probably got lost in the shuffle. There are top-level landing pages for those sections, so no reason not to send people there if JS is disabled.

**Comment by mk-pmb** [comment]
I managed to set up my own copy of the website with the hover fix applied, so for me it's solved, won't care about the official menu anymore. :-)

Thanks for ESlint, and the now great and helpful website!
