### ISSUE TITLE
SEO issues

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint.github.io#31]
This is a list of issues with the site that can improve SEO.
- [ ] Fix page titles. Rule documentation should list rule name, all the pages should include major keywords in the title "JavaScript" and "Linting". Titles should be changed to "ESLint - Pluggable JavaScript linter" or something like that.
- [ ] Page descriptions should be modified to expand on the title. Should also include all major keywords
- [ ] meta keywords should be added.
- [ ] WMT account for both Google and Bing should be registered to add XML sitemap
- [ ] Minor bugs like missing alt tags for images and W3C validation errors should be fixed.
- [ ] Content on the homepage should be expanded.

**Comment by nzakas** [comment]
:+1:

**Comment by ilyavolodin** [comment]
@nzakas Do you mind creating gmail account for eslint and sharing login information with me, so that I could setup WMT (https://www.google.com/webmasters) (or setting up WMT and giving my existing gmail account access to it, if that's supported. Can't remember if it is.).
Btw, just found out that google gives unfair advantage to Google+ accounts, so it might be also worth registering Google+ account for eslint.

**Comment by nzakas** [comment]
Sure, will set it up in the next couple days.

**Comment by ilyavolodin** [comment]
Also, once you set it up, can you give that account access to GA, and my email as well? GA has some additional tooling once WMT is connected to it.

**Comment by nzakas** [comment]
I just set it up - had to move tracking from my old Gmail account to a new one, so might take a bit to set up. I added you to the GA account. Feel free to do whatever you want in there. :)

**Comment by ilyavolodin** [comment]
Thanks. Just got GA invite. Now just need WMT and I can setup XML sitemap which alone should boost rating a bit (since google for some reason only indexed half the site so far, not sure why).

**Comment by nzakas** [comment]
Okay, I'll get that setup.

While we're add it, I think some of the stuff that's in the eslint repo should be moved to be in this repo instead. Basically, anything that doesn't directly have to do with features in ESLint (contribution guidelines, integrations, etc.) I think should live in this repo instead.

**Comment by ilyavolodin** [comment]
Agree. It would also make it much easier to control. I think basically the only thing that should be left in ESLint repo is rules documentation and possibly developers/setup guide

**Comment by nzakas** [comment]
I think also configuring should be in the eslint repo.

In any event, I just setup WMT and added you. Can't link GA and WMT right now for some reason, will have to look into it more later.

**Comment by nzakas** [comment]
Crap, I messed this up by using the wrong Gmail account. Need to fix.

**Comment by nzakas** [comment]
Ugh, I need to delete the WMT account, sorry :( Will recreate in a moment.

**Comment by nzakas** [comment]
Okay, it appears I didn't have to delete it. Should be set.

**Comment by ilyavolodin** [comment]
@nzakas Whenever you have time, could you connect GA to WMT? I can't do that, cause only owner has permissions to do that. Just navigate to GA, go to Acquisitions -> Search Engine Optimization -> Queries and then click on "Setup Webmaster Tools data sharing" and follow instructions from there (the important part is at the very bottom of the page under "Webmaster Tools settings"). This is not urgent, because I want to change documentation layout before doing anything with WMT.

**Comment by nzakas** [comment]
Okay, should be set. It kept getting confused because I have four Gmail accounts open.
