### ISSUE TITLE
"no-template-curly-in-string" should appear in ECMAScript 6 list

### ISSUE THREAD

**Issue by jaredreich** [eslint/eslint.github.io#310]
"no-template-curly-in-string" rule should appear in ECMAScript 6 list (http://eslint.org/docs/rules/#ecmascript-6)

**Comment by vitorbal** [comment]
Thank you for your issue. The rule is indeed preventing a possible error, so I'd say that "trumps" the fact that it is part of the ES6 syntax.

In fact, in my opinion, ES6 is widespread enough nowadays that the rules under the "ECMAScript 6" section could probably all be merged into the other sections. I would like to hear the thoughts on this from the rest of the team, though.

**Comment by platinumazure** [comment]
I agree, personally I think ES6 should be more of a "tag" that can be added to a rule, which supplements the basic categories of "Possible Errors", "Best Practices", and "Stylistic Issues". ES2016, ES2017, and "Variables" could also be tags.

**Comment by not-an-aardvark** [comment]
Closing in favor of https://github.com/eslint/eslint/issues/7991.
