### ISSUE TITLE
Implement OpenSearch?

### ISSUE THREAD

**Issue by Schweinepriester** [eslint/eslint.github.io#318]
Implement <https://en.wikipedia.org/wiki/OpenSearch> for the search?

Background: I'd like to add the search as search shortcut in the browser.

I understand if this is not possible due to Algolia, but I wanted to bring it up.

**Comment by ilyavolodin** [comment]
We can support OpenSearch through google custom site-search. Should be easy enough to add. If you feel like it - send a PR and I'll review it.

**Comment by kaicataldo** [comment]
Closing this issue since we haven't heard anything back for quite some time. Feel free to create a new issue if this is something you would like to discuss further.
