### ISSUE TITLE
ignore-path description is confusing

### ISSUE THREAD

**Issue by alansouzati** [eslint/eslint.github.io#320]
I've tried to follow directions in here:

http://eslint.org/docs/user-guide/command-line-interface#options

and by reading the description of the `ignore-path` option I thought it allowed an actual file path for a file to ignore. After testing it, it is actually the path of the `.eslintignore` file.

Can we update the description of this option in the site?

**Comment by platinumazure** [comment]
Hi @alansouzati, thanks for the issue.

Taking a look at the [`--ignore-path`](http://eslint.org/docs/user-guide/command-line-interface#ignore-path) section, it seems pretty clear to me what the option is for. What particular change would you recommend?

**Comment by alansouzati** [comment]
How about?

> Path of the .eslintignore file (defaults to './eslintignore')

**Comment by platinumazure** [comment]
Right, path to the `.eslintignore` file, not path to a file that should be
ignored.

Sorry, I'm still not understanding what needs to change.

**Comment by alansouzati** [comment]
Sorry, if I'm not making myself clear.

Now that I'm comparing these two pages:

http://eslint.org/docs/1.0.0/developer-guide/nodejs-api
http://eslint.org/docs/user-guide/command-line-interface#options

I understand what you mean about ignore file. This could be my own english limitation, but sorry, the first time I read that I got it as "path to a file to ignore".

Anyways, I still believe the first description is way more clear in the second one.

>  The ignore file to use instead of .eslintignore (default: null). Corresponds to --ignore-path.

Thanks for your help and sorry for my confusion.
