### ISSUE TITLE
Share ESLint Pluralsight course snippet on eslint.org?

### ISSUE THREAD

**Issue by jamischarles** [eslint/eslint.github.io#324]
Hey core ESLint folks.

As always, thank you for the fantastic work you do in building and maintaining a very helpful tool.
I recently published a Pluralsight course on ESLint: https://www.pluralsight.com/courses/eslint-better-code-quality

**2 quick questions**:  
1) **I'd love to share a 5-10 minute video clip of the course**. Maybe "How to install ESLint and get it up and running" or "What is ESLint and why is useful" on ESLint.org.

Your benefit would be a well-made intro video to ESLint, or how to get started. My benefit would be some advertising for my course.

You folks have any interest at all in this?

2) If no to ^, how do you feel about a link to the course on the integrations page, or elsewhere on eslint.org?

Thank you.
Jamis Charles
UI Engineer

**Comment by ilyavolodin** [comment]
I, personally, have no objection to a short clip (5-10 minutes) that we could add to http://eslint.org/docs/user-guide/getting-started page with a link to a complete course, but let's see what others think.

**Comment by nzakas** [comment]
:+1:

**Comment by jamischarles** [comment]
Awesome! I spent 20-30 min and quickly mashed this together:
https://www.youtube.com/watch?v=WULhA-syR0A&feature=youtu.be

Half of this is "Why ESLint". The other half is "Getting started with ESLint".

Any concerns? Any feedback? I'll do some more cleanup after I get some feedback.

Thanks.

**Comment by ilyavolodin** [comment]
Very nice intro. Couple of small nitpicks. You are using very old version of ESLint for this demo and some of the changes are visible (for example, in the more current version of ESLint if you run it without config file present, it will give you a nice message saying to run `--init` command). We also recommend installing ESLint locally, instead of globally. Global installation can cause a lot of problems for beginners when it comes to shareable configs and plugins. And it would be very nice if you would also explain where the users can see rules that are part of `eslint:recommended` config.
I understand that some of those nitpicks might not be possible to change though, since the course is already recorded.
Oh, one other thing at 2:13 the third bullet point should be "Can automatically fix some of those errors":-)

**Comment by jamischarles** [comment]
@ilyavolodin Thank you. This is great feedback. I'll try to make these changes. Shouldn't take too long. Let me know if you have any other comments.

**Comment by jamischarles** [comment]
@ilyavolodin Here's the new version with the changes you asked about:
https://www.youtube.com/watch?v=uwgUqhbVuKM

Let me know if you see anything else glaring. Once you folks are good, I'll issue a PR to embed this on the `getting started` page.

**Comment by ilyavolodin** [comment]
@jamischarles That looks really good. There are a few small nitpicks, but I honestly don't think it's worth the time fixing them (like for example when you ran linting, you used global version of eslint. Or when you were going through `init` command you mention JSX only as part of the React, but JSX is not coupled to React only. Meteor and some other frameworks also use JSX). As I said, I think those problems are very minor and not worth the time to fix them. If you want to create a PR for the `getting started` page with embedded video and a link to your course that would be great.

**Comment by jamischarles** [comment]
@ilyavolodin 
> like for example when you ran linting, you used global version of eslint

Doh. That was a big one. Took 10 min and fixed that one. Leaving the other one as is.
https://www.youtube.com/watch?v=hppJw2REb8g

Thanks! Will issue the PR soon.

**Comment by jamischarles** [comment]
@ilyavolodin qq: I see that the `getting started` page is a markdown page. I'm assuming that I cannot embed a youtube iframe, but need to link a screenshot to my youtube video. Is that correct? Or does html work on that page when it's published?

**Comment by ilyavolodin** [comment]
@jamischarles Here's a link to an article that explains how to include YouTube video from inside markdown: http://www.adamwadeharris.com/how-to-easily-embed-youtube-videos-in-jekyll-sites-without-a-plugin/ I think it would be better if the video would be embedded.

**Comment by jamischarles** [comment]
@ilyavolodin Thank you. I think I got it working simply by using a normal `<iframe>` tag. See PR ^

**Comment by jamischarles** [comment]
It's live! Thanks all.
