### ISSUE TITLE
Add users page

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint.github.io#33]
I really like what Babel did with this page: http://babeljs.io/users/

I'd like to have something similar for the site.

**Comment by ilyavolodin** [comment]
Creating a page is really easy. Getting people to add their logos is a bit trickier.

**Comment by nzakas** [comment]
We just need to seed a few to get the ball rolling.

**Comment by jesstelford** [comment]
To kick it off, my company [Domain.com.au](http://domain.com.au), one of the leading property portals in Australia, uses ESLint.

[Here](https://mega.nz/#!lxZyGb7C!e37obu-sKWqlU9ymXUpedW4HvjiaXQd456YMGOYRBR0) is an SVG logo you can use.

**Comment by nzakas** [comment]
Would you be interested in submitting a PR to create this page?

**Comment by ilyavolodin** [comment]
I'm looking into that right now.

**Comment by nzakas** [comment]
@ilyavolodin <3

**Comment by ilyavolodin** [comment]
How does this look? I didn't create a separate page (we don't really have enough logos for that yet). I just added a carousel to the bottom of the homepage. I added a few companies without permission (well, actually all that I added I don't have permission from except for Domains), but that's was just done for testing.

![eslint](https://cloud.githubusercontent.com/assets/1380062/8610481/90420a0e-2680-11e5-9ad9-fd494b82da61.png)

**Comment by jesstelford** [comment]
@ilyavolodin Looks great! Maybe the title could be "Who's using ESLint?" to remove the corporatey feel (although; it really is a carousel of corporate logos!).

Thanks for putting it together so quick :)

**Comment by nzakas** [comment]
Looks nice, couple notes:

1. :-1:  for the carousel. I'd just let all logos show.
2. I like @jesstelford 's idea about changing the text. That would allow projects to add their logos too.
1. I'd kill the border around the logos.
3. Instead of hardcoding in HTML, I'd suggest using a [data file](http://jekyllrb.com/docs/datafiles/) and render using that. I think that will make it easier to move things around as necessary.
1. We need to use a blue Box logo: https://www.xactlycorp.com/wp-content/uploads/2015/01/box-logo.png
1. Add a "how to add your logo" link to explain how to add them

I think @xjamundx can vouch for PayPal

**Comment by ilyavolodin** [comment]
If you want all of the logos to show, should we do it on the home page, or on the separate page? I though to have a carousel for 3 logos at a time that would either expend to show all logos on click, or link to a separate page with the list of all logos.

**Comment by nzakas** [comment]
Ah, that makes sense. I still wouldn't do a carousel, that's the worst web interaction there is IMHO.

But if you want to show three with a link out to a larger page, that sounds good.

**Comment by ilyavolodin** [comment]
Ok, I'll change it around tomorrow

**Comment by ilyavolodin** [comment]
Ok, here's a new screenshot. I removed carousel, switched to using data file, randomized array of logos. Clicking on "see more" link will expend the container above and show all of the available logos. (box logo still doesn't look right, since it's narrower then the rest, it looks a lot bigger, even thought they all the same height).

![eslint](https://cloud.githubusercontent.com/assets/1380062/8639276/8228f4cc-28a2-11e5-8d75-1725d13f6333.png)

**Comment by nzakas** [comment]
:+1: pretty

**Comment by ilyavolodin** [comment]
Now we need more logos:-) We need at least 4 to start with. We currently have box and Domains only. @nzakas do you want to reach out to some people and ask for permission?

**Comment by nzakas** [comment]
@xjamundx can you get us a PayPal logo?

@zpao would it be OK to put a Facebook logo on this page?

@goloroden can we use a logo for the next web on this page?

@zij can we use a Fitbit logo on this page?

**Comment by jesstelford** [comment]
@ilyavolodin
> randomized array of logos

Love it - will keep it fresh for every visit :)

**Comment by goloroden** [comment]
@nzakas Yes, of course :-)

Feel free to use [this one](http://www.thenativeweb.io/images/brand.png)

**Comment by zpao** [comment]
Feel free to use the logo or if you want the new wordmark instead: https://www.dropbox.com/s/vyhb16c20l8upke/Facebook-06-2015-Blue.png?dl=0

**Comment by ilyavolodin** [comment]
@goloroden Could you provide a larger logo please? Something like 150px height.

**Comment by xjamundx** [comment]
I'll get you the PayPal logo in the morning!

**Comment by goloroden** [comment]
@ilyavolodin Yes, of course :-)

I'll ask our designer about this and get back to you as soon as possible.

**Comment by goloroden** [comment]
![tnw_logo_h150px](https://cloud.githubusercontent.com/assets/906327/8676004/296b4ffa-2a47-11e5-9df0-2b7597904ca3.png)

**Comment by goloroden** [comment]
Here we go: 150px in height, PNG with transparent background.

**Comment by ilyavolodin** [comment]
Awesome, thanks @goloroden
