### ISSUE TITLE
Configuration Cascading and Hierarchy documentation correction?

### ISSUE THREAD

**Issue by wingy3181** [eslint/eslint.github.io#349]
Is it just me or is the following example at http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy incorrect?

> For example, consider `projectA` which has `"root": true` set in the `.eslintrc` file in the main project directory.  In this case, while linting `main.js`, the configurations within `lib/`will be used, but the `.eslintrc` file in `projectA/` will not.
>```text
> home
> └── user
>    ├── .eslintrc <- Always skipped if other configs present
>    └── projectA
>        ├── .eslintrc  <- Not used
>        └── lib
>            ├── .eslintrc  <- { "root": true }
>            └── main.js
>```

I think it should be:

For example, consider `projectA` which has `"root": true` set in the `.eslintrc` file in the **`lib/`** directory.  In this case, while linting `main.js`, the configurations within `lib/`will be used, but the `.eslintrc` file in `projectA/` will not

instead of:

For example, consider `projectA` which has `"root": true` set in the `.eslintrc` file in the **main project** directory.  In this case, while linting `main.js`, the configurations within `lib/`will be used, but the `.eslintrc` file in `projectA/` will not

**Comment by btmills** [comment]
@wingy3181 you're right, good catch! Want to send a PR?

Note that because the site documentation in this repository is autogenerated, this change will need to be made in the [eslint/eslint](https://github.com/eslint/eslint) repository: https://github.com/eslint/eslint/blob/afbea78d4b94839ec6d59d2c98321901aeb76313/docs/user-guide/configuring.md#configuration-cascading-and-hierarchy.

**Comment by wingy3181** [comment]
@btmills 
Raised =)

https://github.com/eslint/eslint/pull/8512

Just a stupid q..so if the docs are autogenerate from the eslint repo, how do they endup in the website repo (eslint.github.io)

**Comment by btmills** [comment]
@wingy3181 thanks! We'll get that landed as soon as the CLA is back up. Sorry about that 😒 

> if the docs are autogenerate from the eslint repo, how do they endup in the website repo

Not stupid at all! The process is not even remotely obvious unless you already know it happens. One of the steps in our release script is [generating the site](https://github.com/eslint/eslint/blob/37e3ba174e66b667fbaebed57cd30a01b307c173/Makefile.js#L584-L737) by processing the files in the [`docs/`](https://github.com/eslint/eslint/tree/master/docs) directory and copying them over to the adjacent `eslint.github.io` checkout, then [committing](https://github.com/eslint/eslint.github.io/commit/684d80a61e23d7480b275f5b817c2bc575d00ddb) them to this repository. That usually happens on our Jenkins build server, so it's mostly automated as part of each release now.

**Comment by Aladdin-ADD** [comment]
seems it can be closed.

**Comment by platinumazure** [comment]
The PR didn't mention the issue, it seems. Closing since this was fixed, thanks!
