### ISSUE TITLE
Serve site over HTTPS

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint.github.io#374]
Currently, eslint.org is not served over TLS. This is because we host the site on GitHub Pages, so we can't directly use a matching TLS certificate.

Every site should be using HTTPS nowadays. Although we don't host any confidential data, serving the site over HTTPS prevents people on the network from listening to or tampering with the connection. For more details on why all sites should use HTTPS, see https://doesmysiteneedhttps.com/.

Starting in Chrome 62, all insecure sites with input fields (including eslint.org) will cause a "Not secure" warning to be displayed in the URL bar. This creates a poor impression for our users.

I think we should start using [Cloudflare](https://www.cloudflare.com/) as a reverse proxy to the GitHub Pages server. This will allow us to start serving the site over HTTPS for free, and is extremely simple to set up. (It will also give us other benefits, such as faster pageload times due to being served over Cloudflare's CDN.)

**Comment by platinumazure** [comment]
:+1: As long as it's easy and free, I would love to see this done. Also, I keep linking to a nonexistent https site from GitHub and Gitter by accident...

**Comment by gyandeeps** [comment]
This was very easy... i did on my website and it took me a minute. 
https://gyandeeps.com/

**Comment by not-an-aardvark** [comment]
**TSC Summary:** This issue proposes serving eslint.org through Cloudflare, which would allow us to serve the site over HTTPS for free (and avoid "not secure" warnings in upcoming versions of Chrome).
**TSC Question:** Should we accept this proposal?

**Comment by alberto** [comment]
I'd prefer to use [netlify](https://www.netlify.com/open-source/) instead. There are a few [other OSS projects](https://www.netlify.com/open-source/) using it already.

**Comment by not-an-aardvark** [comment]
I'm unfamiliar with netlify. What are the advantages of using it over Cloudflare?

I like Cloudflare for a few reasons (roughly in order of priority):

1. It's free and allows us to use HTTPS on the site.
1. It lets us keep our current workflow of pushing to a GitHub repo and having the site build automatically.
1. We can redirect all HTTP traffic to HTTPS.
1. It's easy to set up.
1. It has some nice features such as being able to rewrite all HTTP links to HTTPS, and set a HSTS header.

If those are also possible with netlify then I have no objection to using it instead.

**Comment by alberto** [comment]
I think it has all that features. I prefer the way it handles [certificates](https://www.netlify.com/docs/ssl/#netlify-certificates), by generating Let's encrypt certificates, rather than the[ cloudflare approach ](https://support.cloudflare.com/hc/en-us/articles/200170416-What-do-the-SSL-options-mean-).

It has some additional [features](https://www.netlify.com/features/) that can come handy:
- Continuous Deployment with custom build command
- Deploy previews, which can make reviewing UI changes much easier.
- Client-side Routing Support
- Instant Rollback

**Comment by not-an-aardvark** [comment]
I'm a bit confused -- if we used netlify, would we still be hosting the site on GitHub Pages? Or would it be a separate service?

Cloudflare is a bit different because it just acts as a reverse proxy, and it would still be getting the content from GitHub Pages. I wouldn't necessarily be opposed to looking into GitHub pages alternatives, but that seems like a separate proposal from just adding a service like Cloudflare as a middleman.

**Comment by alberto** [comment]
It would replace github pages, but the setup is really straightforward.

**Comment by not-an-aardvark** [comment]
In [today's TSC meeting](https://github.com/eslint/tsc-meetings/blob/497d7506dc7c6d73295bdeae468d8b81f575b292/notes/2017/2017-08-17.md#serve-site-over-https), we decided to start using Cloudflare. People seemed open to the possibility of switching backends, but that seems like a larger task and can be done as part of a separate issue.

The next step is to set up Cloudflare. I can handle creating a Cloudflare account, but someone with access to the `eslint.org` domain will need to point it at Cloudflare's servers. @ilyavolodin, do you have access to the `eslint.org` domain?

**Comment by ilyavolodin** [comment]
@not-an-aardvark No, I don't. I think that's more or less the only thing I don't have access to. I know @nzakas used to own the domain, but I think it was transferred to JSF. @kborchers is showing up as a contact person for the domain, so I assume that he has access to the DNS records.

**Comment by kborchers** [comment]
You should definitely reach out to us on issues like this (anything around infrastructure, security, potential to cost money) before you spend lots of time on them. We already use Cloudflare for all of our domains and can get you set up to serve over https in no time.

**Comment by not-an-aardvark** [comment]
Thanks @kborchers, I'll keep that in mind for the future. I hadn't realized the JSF was already using Cloudflare.

Would you mind setting up `eslint.org` and `cn.eslint.org` up with Cloudflare?

**Comment by kborchers** [comment]
You should be all set. Looks like there is some mixed content on the `cn.eslint.org` home page so you'll probably want to scan both sites for images, etc that have `http` addresses.

**Comment by gyandeeps** [comment]
thanks a lot @kborchers ... Did you also add a rule to route `http` traffic to `https` ?

**Comment by kborchers** [comment]
@gyandeeps yes, it is set to always use `https`. Looks like there may be an issue with the `cn` subdomain and https though. Looking into it

**Comment by not-an-aardvark** [comment]
It seems to be working for me -- could it just be a DNS cache issue?

**Comment by kborchers** [comment]
@not-an-aardvark Perhaps. I'll give it a bit and check again.

**Comment by not-an-aardvark** [comment]
In any case, thanks very much for your help!

**Comment by not-an-aardvark** [comment]
@kborchers It looks like https://jenkins.eslint.org/ no longer resolves to our jenkins server (it's returning a DNS error). Is it possible that the entry for `jenkins.eslint.org` was changed somehow?

**Comment by kborchers** [comment]
Should be fixed.

**Comment by not-an-aardvark** [comment]
Closing this issue because everything seems to be working. Thanks again!
