### ISSUE TITLE
Search bar fails with a type error

### ISSUE THREAD

**Issue by bwhitty** [eslint/eslint.github.io#422]
![screen shot 2017-10-11 at 4 31 59 pm](https://user-images.githubusercontent.com/1571966/31472155-e60c2144-aea1-11e7-9831-c6eea1d1dad8.png)

This happens in both FF 57 and Chrome 61

**Comment by ilyavolodin** [comment]
Thanks for the report. I'm looking into it now. It's related to PWA changes we pushed earlier today.

**Comment by ilyavolodin** [comment]
This is now fixed (we reverted PWA until we can fix it). Closing

**Comment by bwhitty** [comment]
Anyone who accessed the site while it's broken now has a zombie service worker installed for this site and so it continues to be broken today for those users.

<img width="1680" alt="screen shot 2017-10-16 at 12 50 29 pm" src="https://user-images.githubusercontent.com/1571966/31624432-af387852-b270-11e7-8512-e3f60d70aa0a.png">

Opening the site in an incognito window or manually deleting the cache files from "workbox-precaching" fixes this.

**Comment by not-an-aardvark** [comment]
You can manually unregister it by entering this into the dev console:

```js
navigator.serviceWorker.getRegistrations().then(workers => workers.forEach(worker => worker.unregister()));
```

Obviously, we don't want every user to need to enter something into the dev console as a long-term strategy. Is there a good way to keep service workers up-to-date (aside from pushing an update that unregisters all of them)?

**Comment by bwhitty** [comment]
I'm not sure of a solution off the top of my head. Here's my favorite talk about the subject, I vaguely remember it discussion this issue: https://www.youtube.com/watch?v=CPP9ew4Co0M
