### ISSUE TITLE
bug: demo configuration not shown

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint.github.io#432]
![image](https://user-images.githubusercontent.com/13050025/31781220-83e71278-b52a-11e7-9a26-680521af8a6f.png)

click configuration => not working.

**Comment by christalk** [comment]
Yes, I tried with FireFox, IE, Google Chrome and it still doesn't work.
https://eslint.org/
https://eslint.org/demo/
The "Rules Configuration" (ESLint v4.9.0) doesn't give any screen , nor informations

https://eslint.org/demo/#configuration

**Comment by christalk** [comment]
In the Demo -> **ESLint Demo**, I got a **407 error** with this link (Rules Configuration)
https://cdn.jsdelivr.net/g/lodash@3.10.1,hogan.js@3.0.2,algoliasearch@3.8.1,autocomplete.js@0.12.0(autocomplete.min.js)


But, in the Demo -> **Espree Demo**, I got **no error** with the same ? link (Parser Configuration)
https://cdn.jsdelivr.net/g/lodash@3.10.1,hogan.js@3.0.2,algoliasearch@3.8.1,autocomplete.js@0.12.0(autocomplete.min.js)

**Comment by christalk** [comment]
Just one point : 

Demo -> **ESLint Demo** -> **Rules Configuration** -> **doesn't work**
https://eslint.org/demo/#configuration


Demo -> **Espree Demo** -> **Parser Configuration** -> **works**
https://eslint.org/parser/#configuration

**Comment by christalk** [comment]
Thank you, it works now !
