### ISSUE TITLE
Improve "Getting Started" page?

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint.github.io#447]
Original issue created as eslint/eslint#8420.

Quoting from the original issue:

> I am also hoping to see a better explanation of the [**Getting Started** article](http://eslint.org/docs/user-guide/getting-started), including:
> 
> - Explicitly say each rule do not support multiple options.
> - Explicitly say each rule has the potential to support unique severity beyond what we have.
> - A list of all options that each rule has. Currently, the options are written in the docs, but they are hard to distinguish against other similarly formatted text or code.
> - **Windows** users are being left out. Some of us, like me, are restricted to use Windows due to work. What is lacking is, for example, where the configuration files are at, and how to create a new `.eslintrc` manually without using `eslint --init` command (renaming a file as `.eslintrc.`, with 1 period at the beginning and end of the filename each).
> 
> I'm very certain there may be a duplicate issue, but the most important one is the point in boldfaced text.

I agree that the Getting Started section deserves another look. Or, maybe we should keep Getting Started very high-level and then point to more of a "cookbook" page that goes into some more detail about how to do some setup and tasks. We definitely need to give this some thought, at any rate.

**Comment by mysticatea** [comment]
I agree that the Getting Started page needs improvement.

But I think "Windows users are being left out" is a misunderstanding. The `.eslintrc.` matter is not a restriction of Windows but a restriction of `explorer.exe`. Editors such as VSCode, Atom, or Sublime Text can create `.eslintrc` file without problem. I'm not sure that we should write about `.eslintrc` in `explorer.exe` because it has been deprecated. Currently `.eslintrc` needs an extension (`.js`, `.yml`, or `.json`).

**Comment by platinumazure** [comment]
@mysticatea Yes, you're absolutely right. The fact that we don't mention the extensions shows how little care we've put into that section/page.

**Comment by mysticatea** [comment]
Ah, oh, I got it. The Getting Started page has shown the deprecated feature...

**Comment by platinumazure** [comment]
I made some improvements recently, but I'm not sure if we should be considering a new/different approach to how that page should present its information. I would love to hear what others think!

**Comment by platinumazure** [comment]
I haven't heard anything from the rest of the team on this, and this hasn't been a priority for me either, so I'm going to go ahead and close this.
