### ISSUE TITLE
click search result, go to docs/3.0.0

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint.github.io#475]
it is expected to open the latest version.

![image](https://user-images.githubusercontent.com/13050025/39847956-edf2f9ce-5436-11e8-849f-c313e62cd961.png)

**Comment by ilyavolodin** [comment]
Yes, I noticed that too. It has something to do with this line: https://github.com/eslint/eslint.github.io/commit/6d951fdfb6ac8e28ba11d32d70b6117e7ac83e98#diff-7693eb643e8fe8b8d46b407909b408ceR31 but I haven't had a chance to dig into DocSearch documentation yet to figure out how to correct it.

**Comment by Krinkle** [comment]
This is actively causing 404 Not Found errors for users, making it rather difficult to find things.

Example: search for "for-direction".

| Search | Result | 404
|--|--|--
|<img width="607" alt="screen shot of search query" src="https://user-images.githubusercontent.com/156867/41059069-75c7214e-69c3-11e8-933b-719890058d2c.png"> |<img width="685" alt="screen shot " src="https://user-images.githubusercontent.com/156867/41059112-925fea66-69c3-11e8-9394-8beea6472001.png">| <img width="798" alt="screen shot of 404 page with url" src="https://user-images.githubusercontent.com/156867/41059124-9a7db3fe-69c3-11e8-89da-e97f57f3fe59.png">

This claims to be the 3.0.0 rules page, but links to `for-direction` which was introduced in ESLint 4.

**Comment by platinumazure** [comment]
I'm looking into this. I think I understand the issue, though I need to confirm a few things before I try to make any changes.

We'll also need to document necessary changes to docsearch configs (in https://github.com/algolia/docsearch-configs) as part of major releases. That will go in the maintainer guide.

**Comment by platinumazure** [comment]
I've opened a PR on the docsearch-configs repo (algolia/docsearch-configs#440). The idea is to explicitly only index the "current version" of ESLint docs and not index old versions.

In that PR, I can't start from /docs because that page does not exist in the repo. So I'm starting from /docs/rules, /docs/user-guide, /docs/developer-guide, and /docs/maintainer-guide (all of which should exist). There might be other improvements we could make, but that PR (or something similar) should help fix most of the issues.

Note that we also need to make a change here in eslint.github.io (on the docsearch/autocomplete client-side configuration), so we would need to merge PRs in both repositories on the same day to avoid inconsistencies.

**Comment by platinumazure** [comment]
We've merged the docsearch-configs change and the eslint.github.io change. Unfortunately I didn't think about the fact that the scraper probably hasn't run yet so we have the eslint.github.io changes running against the old index. It will resolve itself after the next scraper run.

I'll check tomorrow to see how the search experience looks, then either close this issue or open new PRs against this issue as needed.

Apologies for any inconvenience as we're rebuilding our search config.

**Comment by Krinkle** [comment]
@platinumazure Yep, the search seems to be working well again. Thanks!

I do note that <https://eslint.org/docs/3.0.0/rules/> still lists `for-direction` in the table, linking to a 404 Not Found. I've filed https://github.com/eslint/eslint.github.io/issues/486 for that.

**Comment by platinumazure** [comment]
Thanks for confirming @Krinkle.

I'm going to leave this open for a few days in case I want to make any more PRs to tweak the search configuration.

**Comment by platinumazure** [comment]
I wrote algolia/docsearch-configs#457 to avoid indexing of blog headers, since those are identical in every post.

Closing as the main issue is resolved.
