### ISSUE TITLE
Error while installing eslint

### ISSUE THREAD

**Issue by jankhunter** [eslint/eslint.github.io#493]
<img width="826" alt="screen shot 2018-07-06 at 6 17 17 pm" src="https://user-images.githubusercontent.com/32759296/42379845-c9d1703a-8149-11e8-9895-36e976b4fa6b.png">

I am getting the above error while i install eslint. 

When i look into the same file of previous version of eslint, i am not having those three dots.
Those three dots are in multiple lines. 
Is this a known issue?

**Comment by Aladdin-ADD** [comment]
what is your Node.js version? ESLint v5 drop support Node 4, 5, 7.
see https://github.com/eslint/eslint/blob/master/package.json#L126

**Comment by jankhunter** [comment]
Yes. That was the issue. After updating node version, i reinstalled eslint and is working fine now. Thanks @Aladdin-ADD

**Comment by platinumazure** [comment]
Closing as this issue appears to be resolved.
