### ISSUE TITLE
Create a /team page

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint.github.io#515]
Create a page at /team that lists out the ESLint team. This should have three sections:

* Technical Steering Committee
* Committers
* Alumni

I envision each section as a heading with images/names/GitHub usernames, similar to the [Babel page](https://babeljs.io/team). Unlike the Babel page, I don't think having a Twitter username is useful, but open to other opinions on that.

I'm pretty sure this can be built automatically using the GitHub API and a script, so that would be my approach.

**Comment by not-an-aardvark** [comment]
Should this issue be closed now that https://github.com/eslint/eslint.github.io/pull/526 is merged?

**Comment by nzakas** [comment]
I was going to close it with this PR: https://github.com/eslint/eslint/pull/11152
