### ISSUE TITLE
No mention of required "plugin:" prefix for using configs from plugins

### ISSUE THREAD

**Issue by edg2s** [eslint/eslint.github.io#525]
This section on configs in plugins:
https://eslint.org/docs/developer-guide/working-with-plugins#configs-in-plugins

tells you how to create a config in a plugin, but not the syntax for using it, which is:

`"extends": "plugin:myPlugin/myConfig"`

**Comment by platinumazure** [comment]
Hi @edg2s, thanks for the issue.

We talk about how to extend from a plugin config in our ["Configuring ESLint" user guide](https://eslint.org/docs/user-guide/configuring#using-the-configuration-from-a-plugin), but I think it would be valuable to mention it quickly (and/or link to the other section) from the Working with Plugins page.

That said, any change would need to be made in the [main ESLint repository](https://github.com/eslint/eslint), specifically to [this file](https://github.com/eslint/eslint/blob/master/docs/developer-guide/working-with-plugins.md). As part of the ESLint release process, the documentation in the ESLint repo will be copied into this repository. Any changes made to the plugin documentation in this repository will be overwritten on our next release.

**Comment by kaicataldo** [comment]
Closing this issue since we haven't heard anything back for quite some time. Feel free to create a new issue if this is something you would like to discuss further.
