### ISSUE TITLE
Search results getting trimmed

### ISSUE THREAD

**Issue by varundey** [eslint/eslint.github.io#531]
When searching the docs for something which has multiple matches, the results flows out of the browser and thus gets trimmed. There is no way I can scroll down the search results. 

<img width="544" alt="screen shot 2019-01-03 at 5 32 25 pm" src="https://user-images.githubusercontent.com/9202135/50636937-01159b80-0f7e-11e9-9a6a-6705b0df86f4.png">

**Comment by platinumazure** [comment]
Hi @varundey, thanks for the issue!

When you do scroll the page, what happens? Is the issue that the overall site header is fixed, so the search results never move relative to the viewport (i.e., you always see the top of the search results even if you scroll the rest of the site)? Thanks!

**Comment by varundey** [comment]
Sorry should have specified that in the original issue. Yes your assumption
is correct. The header is fixed and when I try to scroll, the page in the
background starts scrolling and the result container is static.

**Comment by varundey** [comment]
@platinumazure Also if you have not already started working on it, I'd like
to give it a try.

>

**Comment by platinumazure** [comment]
@varundey I haven't started yet, please feel free to take a look!

I recommend looking at the DocSearch documentation; there may be an option somewhere that will ensure the container is scrollable. I think that will be better than making the ESLint site header non-fixed. But let us know what you come up with.

**Comment by varundey** [comment]
Well this is weird. Turns out, this bug is coming from DocSearch itself. I went to https://community.algolia.com/docsearch/ and tried searching for something, and woot, I could repro the bug on their site 😄 
![screen shot 2019-01-03 at 11 08 25 pm](https://user-images.githubusercontent.com/9202135/50652523-c119dd00-0fac-11e9-893e-c7e9abd980e5.png)

**Comment by platinumazure** [comment]
Nice find! Maybe it's worth searching their GitHub repository for issues related to this; and if none exist, maybe you could create one? Thanks!

**Comment by varundey** [comment]
Yep. That is what I intended to do after commenting here. Seems this issue is across all the platforms that use DocSearch (bootstrap, react etc.) 😄

**Comment by kaicataldo** [comment]
Closing this issue since it stems from DocSearch's current behavior. Please feel free to make a new issue if there's something we can do here!
