### ISSUE TITLE
no-param-reassign "Version" section problem

### ISSUE THREAD

**Issue by cvrebert** [eslint/eslint.github.io#54]
http://eslint.org/docs/rules/no-param-reassign contains the text "## Version" under the "Further Reading" section. Presumably the start of a new section entitled "Version" was intended instead.

**Comment by ilyavolodin** [comment]
Thanks for the report. I think that might be because no-param-reassign is missing empty line at the end of the file. I'll verify.

**Comment by ilyavolodin** [comment]
This issue has been fixed. Closing.
