### ISSUE TITLE
bug: espree demo not working

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint.github.io#546]
https://eslint.org/parser/
![image](https://user-images.githubusercontent.com/13050025/53690725-27ec2480-3dab-11e9-8eef-b3c9bb24e30b.png)

it could be caused by https://github.com/eslint/eslint/commit/db0c5e2a7f894b7cda71007b0ba43d7814b3fb2e.

**Comment by g-plane** [comment]
We can create a separate build for `espree` instead of using `eslint.js` file.

**Comment by g-plane** [comment]
It's still broken due to the website how does "import" the `espree` and use it.

**Comment by aladdin-add** [comment]
Given espree.js is a umd, I suppose changing `espree = require("espree")` to `espree = window.espree` will fix the issue.

**Comment by g-plane** [comment]
Another solution may be use webpack as well. (And we can also use ES6 `import`.)
