### ISSUE TITLE
Website plugin docs route is broken

### ISSUE THREAD

**Issue by amypellegrini** [eslint/eslint.github.io#549]
I tried, to access the following URL in the website docs:

https://eslint.org/docs/developer-guide/working-with-plugins/

But I get a 404 page. I clicked on "Edit this page" and I was directed to the 404 page in the code.

Looking through the repo I can see there is actually a page doc (https://github.com/eslint/eslint.github.io/blob/master/docs/5.0.0/developer-guide/working-with-plugins.md), but for some reason is not being properly routed or built.

**Comment by aladdin-add** [comment]
it's working if removed the last "/": https://eslint.org/docs/developer-guide/working-with-plugins

**Comment by amypellegrini** [comment]
Mmm, this is weird, I recall removing the end slash from the URL and still getting 404, and I also recall clicking from the menu and getting 404, but I cannot reproduce anymore.

Anyway, it doesn't seem to be happening anymore!

Thanks and apologies for the annoyance.
