### ISSUE TITLE
Demo does not offer 2019 ECMA Version

### ISSUE THREAD

**Issue by RyanZim** [eslint/eslint.github.io#561]
The ECMA Versions available in the demo are 3, 5, 2015, 2016, 2017, & 2018. 2019 should be an option as well.

**Comment by kaicataldo** [comment]
Agreed! We just haven't gotten to it yet. PRs are welcome!

**Comment by AlokTakshak** [comment]
@kaicataldo Do we need to add jest 2019 in the Ecma version dropdown?
![image](https://user-images.githubusercontent.com/26347838/57189253-c3c01b00-6f29-11e9-9981-45ffd748164b.png)

**Comment by AlokTakshak** [comment]
#562

**Comment by RyanZim** [comment]
Fixed in https://github.com/eslint/eslint.github.io/pull/562.
