### ISSUE TITLE
Create a section of the site with links to tutorials

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint.github.io#57]
There's already a few tutorials/articles out there on how to setup ESLint. It would be nice to have a section of the site with those links. Some of them explain how to configure ESLint much better then our documentation does. Although, maybe the goal should be to have our documentation be better then those articles?:-)

**Comment by nzakas** [comment]
:+1:

**Comment by ilyavolodin** [comment]
I can add that page in, and collect a few links. But I just wonder if we should write our own quick guide sort of thing, and then link to those other articles for more information. What do you think?

**Comment by nzakas** [comment]
Probably a good idea, though it would be weird to link out from our own guide and say "for more info, see stuff we didn't write." I'd probably keep the two separate.

**Comment by ilyavolodin** [comment]
We added getting started page, I think that's good enough. At this point, there are too many tutorials out there to link to them all.
