### ISSUE TITLE
eslint.org serving invalid TLS cert

### ISSUE THREAD

**Issue by dudeofawesome** [eslint/eslint.github.io#584]
![image](https://user-images.githubusercontent.com/1683595/60140325-3a2d0c80-9766-11e9-81d6-9e997ae912d1.png)

Looks like the default Netlify cert is being served instead of the eslint.org one.

**Comment by not-an-aardvark** [comment]
Thanks for the report. We're currently doing some [maintenance](https://twitter.com/geteslint/status/1143610639807647744) on eslint.org as we migrate backends, so some downtime/certificate errors are expected as the DNS changes gradually propagate. In the meantime, you can use https://eslint.netlify.com/ for a mirror of the site with a valid certificate.

**Comment by dudeofawesome** [comment]
Thanks! Just wanted to make sure you guys were aware.

**Comment by kaicataldo** [comment]
This should now be fixed!
