### ISSUE TITLE
User Guide has incorrect example code comments in "unicode-bom" rule page

### ISSUE THREAD

**Issue by BrandonYeager** [eslint/eslint.github.io#589]
The example code in the page for the `unicode-bom` rule has incorrect comments (https://eslint.org/docs/rules/unicode-bom#require-or-disallow-the-unicode-byte-order-mark-bom-unicode-bom).

The "always" examples should say `/*eslint unicode-bom: ["error", "always"]*/`
The "never" examples should say `/*eslint unicode-bom: "error"*/`

---

See screenshot for a clearer explanation...

![unicode-bom_UserGuideErrors](https://user-images.githubusercontent.com/6868375/60541447-4cafc480-9cd7-11e9-9bc6-0b04b8025cb4.png)

**Comment by kaicataldo** [comment]
Nice catch! This does indeed seem to be a bug. Our documentation actually live in https://github.com/eslint/eslint (we copy over those files to this repo when we run releases). Do you mind making an issue over there? PRs are always welcome, as well!

**Comment by BrandonYeager** [comment]
Done! (https://github.com/eslint/eslint/issues/11937)

I'll look into submitting a PR. I haven't done a lot of collaboration on open source projects, so I'll see if I can figure it out. Thanks for reply and the direction! I really appreciate how quickly you guys respond to issues!

**Comment by kaicataldo** [comment]
That's fantastic! Hopefully our [documentation](https://eslint.org/docs/developer-guide/contributing/) answers any questions you have, but please feel free to comment on the issue or visit [our chat](https://gitter.im/eslint/eslint) if you any questions! 

I'm going to close this issue in favor of the new one.
