### ISSUE TITLE
Site was not regenerated correctly for 0.19.0 release

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint.github.io#59]
Stuff is missing that should've been there. Like my commit: https://github.com/eslint/eslint/pull/2204 doesn't seem to be present in the new version of the site. Not sure what went wrong.

**Comment by nzakas** [comment]
Weird. I did have some trouble with site generation during the release, but I thought I fixed the problems. Here's the commit: https://github.com/eslint/eslint.github.io/commit/90af43c07e1b23b0ce70dbe60c4c6ca07cd8e2b1

Anything else missing?

**Comment by ilyavolodin** [comment]
I spot-checked a few other commits, and mine seems to be the only one missing. Don't know why.

**Comment by ilyavolodin** [comment]
@nzakas There's still some problem with site generation. 0.20.0 should've included `linebreak-style` however, README in rules hasn't been updated with it... I'll try to regenerate the site right now and see if it will work for me.

**Comment by ilyavolodin** [comment]
Nevermind. I was under the impression that `linebreak-style` made it into 0.20.0 release, but it didn't.

**Comment by nzakas** [comment]
Can we close this now?

**Comment by ilyavolodin** [comment]
Yes. Closing.
