### ISSUE TITLE
Add Anchor links to sections in the docs

### ISSUE THREAD

**Issue by bryanbraun** [eslint/eslint.github.io#67]
It would be nice to link [directly](http://ux.stackexchange.com/questions/36304/use-of-mouse-over-paragraph-marker-in-headlines-for-permalink) to various sections in the docs and developer guide via anchor links.

I happen to maintain [a tool](http://bryanbraun.github.io/anchorjs/) that helps with that and would be happy to help set it up.

**Comment by ilyavolodin** [comment]
I was planning on adding links to sections at some point. All of our documents already have anchors, since they are generated from .md files by jekyll, we just don't expose a menu anywhere yet.

**Comment by bryanbraun** [comment]
I've added a PR with one possible approach.
