### ISSUE TITLE
0.22.0 and 0.22.1 blog posts incorrectly dated

### ISSUE THREAD

**Issue by rabbitfang** [eslint/eslint.github.io#70]
The blog posts for the 0.22.0 and 0.22.1 releases are dated the 30th of June, 2015, which has not yet occurred. They should be dated for the 30th of *May*, 2015.

**Comment by nzakas** [comment]
Oops, thanks for the heads up! @ilyavolodin do you have time to fix this?

**Comment by ilyavolodin** [comment]
I will try to do it tonight. Was planning on fixing it yesterday, but...
