### ISSUE TITLE
eol-last documentation page is confusing

### ISSUE THREAD

**Issue by PiPeep** [eslint/eslint.github.io#74]
Compare: http://eslint.org/docs/rules/eol-last
With: https://github.com/eslint/eslint/blob/master/docs/rules/eol-last.md

The newlines got stripped in the code block, making the examples impossible to understand.

**Comment by gyandeeps** [comment]
I think we need to just get rid of the last 2 examples.

**Comment by nzakas** [comment]
Either way, this is an issue for the ESLint repo, since that's where the docs live.

**Comment by gyandeeps** [comment]
@PiPeep Can you please log this issue here: https://github.com/eslint/eslint/issues
and then close this one.
thanks
