### ISSUE TITLE
Add Espree Parser

### ISSUE THREAD

**Issue by xjamundx** [eslint/eslint.github.io#77]
Let's do an updated version of this using espree:
http://esprima.org/demo/parse.html

We could borrow the style used here:
https://babeljs.io/repl/

**Comment by xjamundx** [comment]
This is super cool:
http://felix-kling.de/esprima_ast_explorer/

**Comment by IanVS** [comment]
Very nice indeed! Looks like he's planning to add other parsers as well (Espree included): https://github.com/fkling/esprima_ast_explorer/issues/20

**Comment by fkling** [comment]
I'm almost there, will publish something in the next few days.

I was also thinking to support eslint plugin prototyping. Currently, when you click the transform button, you will get jscodeshift for generic AST-to-AST transform stuff. But if I generalize this a bit, then the "transform" could be interpreted as eslint plugin (and load and run eslint). It should be relatively easy then to add new tools. That's a bit further down the road though.

**Comment by fkling** [comment]
Added espree and got a shine new domain: http://astexplorer.net/.
