### ISSUE TITLE
Lint es6 code in demo

### ISSUE THREAD

**Issue by Semigradsky** [eslint/eslint.github.io#80]
Please, add more [Environments](http://eslint.org/docs/user-guide/configuring#specifying-environments) to [demo page](http://eslint.org/demo/).

![image](https://cloud.githubusercontent.com/assets/1198848/8404328/ca6a752e-1e54-11e5-9839-65a5093d25c5.png)

![image](https://cloud.githubusercontent.com/assets/1198848/8404345/e31b363a-1e54-11e5-9bbe-96e42ce992d4.png)

**Comment by nzakas** [comment]
es6 environment doesn't work inline due to https://github.com/eslint/eslint/issues/2705

Are there other environments you'd like added?

**Comment by Semigradsky** [comment]
I would like to be able to lint es6 code. It seems that `es6` environment should allow it.

In the list rules there are rules specific to es6:
![image](https://cloud.githubusercontent.com/assets/1198848/8413320/5d15ac48-1e98-11e5-8fb5-922f4aca3e6d.png)
But I see `Unexpected token const` error

**Comment by nzakas** [comment]
Please see the issue I linked in my previous comment for discussion of why it doesn't work.

**Comment by ilyavolodin** [comment]
Environments in the demo are not supplied inline, so es6 should work. However, I did try to get it to work some time ago, and I couldn't figure it out. I'll give it a try again at some point (probably when we'll be ready to merge in Espree demo).

**Comment by xjamundx** [comment]
Yeah I'd love to help get this working. Maybe I'll work on this and the espree demo thing again.

**Comment by xjamundx** [comment]
I think I figured it out...will issue a PR tomorrow

**Comment by mzgol** [comment]
It still doesn't work for me: #137.
