### ISSUE TITLE
Demo: Should also include rule name in the error messages

### ISSUE THREAD

**Issue by gyandeeps** [eslint/eslint.github.io#85]
I think it would be a good idea to include rule names inside the error messages. It will be consistent based on how eslint works and also it helps to find out which rule is throwing errors.

**Comment by ilyavolodin** [comment]
Rule names are shown if you mouse over red dots on the right side of the editor. But, yes, we should also include them in error messages. I haven't been paying attention to the demo, because I'm planning a full re-write for it at some point.

**Comment by gyandeeps** [comment]
Sounds good.
