### ISSUE TITLE
Demo: an ability to specify code with URL.

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint.github.io#99]
I want to use demo to report issues.
I'm happy if I can specify code with URL.

Such as:

```
http://eslint.org/demo/#code=var%20foo%20%3D%20%22Hello%20World!%22
```

``` js
var foo = "Hello World!";
```

**Comment by gyandeeps** [comment]
I like it. Its so handy when I want to share it with people.
I know esprima does it on their website.

**Comment by ilyavolodin** [comment]
Yes, it's on my todo list. It's just not that simple, because rule configuration matters a lot. And we have a lot of rules and options. I don't think it all will fit on query string, so we probably need to get a database to store configuration + code and output a token.

**Comment by nzakas** [comment]
Eek, I really wanted to keep the site static for simplicity - otherwise we will be spending time debugging why the DB connection is slow, broken, etc.

**Comment by ilyavolodin** [comment]
I wasn't planning on making the site dynamic. Just exposing a web service,
that can be called to save and retrieve examples.

**Comment by nzakas** [comment]
Yup, that's what I was referring to...why introduce something that could break? The demo isn't really meant to be anything more than just that, a demo to try it out. I think doing anything more than the query string solution is a lot of work for very little gain and maintenance headaches.

**Comment by ilyavolodin** [comment]
My idea for this change was to turn demo into a bug reporting tool as well. It would be much easier and quicker to ask people to reproduce their issue in the demo, and past URL into github issue, then chase them for version of ESLint, .eslintrc and error messages that they are seeing.
I originally hoped to find some free service that just allows arbitrary key-value pair storage and retrieval, but I couldn't find anything out there that does this.

**Comment by guerrero** [comment]
I think that it can be easy to implement this functionality with JavaScript, due that Jekyll is a static site generator there's no other way to achieve it. We can use a library like [URI.js](https://medialize.github.io/URI.js/) or use plain vanilla JavaScript and `window.location.href`. But the steps are basically the same:

To share a link:
- Iterate over the rules to check which of them are active and store them in a dictionary
- Get the content of the editor and store it in another variable
- Convert them to an URL query using a library
- Optionally we can add an eventListener to update the website when the editor content or a rule changes but I think that it wouldn't be a good idea

To get info from a URL query:
- Parse the query and to the inverse process but checking before if a rule exists and if that's not the case append all the errors to a notification panel that can be placed above the editor

Ok, I'm sure that it wouldn't be as easy as it seems but I can try to implement it if no one is working on this, it will took me more than week but I want to try to achieve it.

**Comment by vitorbal** [comment]
@guerrero the new version of the demo which is react-based is now live, so if you're still interested on implementing the "load from URL" feature, i'd say go for it!
